import { 
  doc, 
  getDoc, 
  setDoc, 
  collection, 
  getDocs, 
  query, 
  where, 
  deleteDoc, 
  addDoc
} from 'firebase/firestore';
import { db } from './firebase';

export interface AppConfig {
  showDemoData: boolean;
  priceBasic?: number;
  priceSilver?: number;
  priceGolden?: number;
  priceSponsored?: number;
  pricePushNotifications?: number;
  priceHomepageBanner?: number;
  priceNfcStands?: number;
  priceSocialMedia?: number;
}

export const DEFAULT_APP_CONFIG: AppConfig = {
  showDemoData: false,
  priceBasic: 0,
  priceSilver: 5,
  priceGolden: 12,
  priceSponsored: 15,
  pricePushNotifications: 10,
  priceHomepageBanner: 25,
  priceNfcStands: 8,
  priceSocialMedia: 50
};

export async function getAppConfig(): Promise<AppConfig> {
  if (!db) return DEFAULT_APP_CONFIG;
  try {
    const configDoc = await getDoc(doc(db, 'settings', 'appConfig'));
    if (configDoc.exists()) {
      return { ...DEFAULT_APP_CONFIG, ...configDoc.data() } as AppConfig;
    }
  } catch (err) {
    console.warn("Could not fetch appConfig:", err);
  }
  return DEFAULT_APP_CONFIG;
}

export async function setAppConfig(config: Partial<AppConfig>): Promise<void> {
  if (!db) return;
  try {
    await setDoc(doc(db, 'settings', 'appConfig'), config, { merge: true });
  } catch (err) {
    console.error("Error setting appConfig:", err);
  }
}

export const DEMO_SEED_DATA = {
  // 20 Businesses in Irbid
  businesses: [
    {
      isDemo: true,
      name: 'كافيه لافا (Lava Specialty Coffee)',
      category: 'مطاعم ومقاهي',
      description: 'مقهى مختص بالقهوة الساخنة والباردة والمشروبات المبتكرة وجلسات هادئة ممتازة للدراسة والعمل.',
      address: 'شارع الجامعة، مقابل البوابة الشمالية لجامعة اليرموك، إربد',
      phone: '0788123456',
      whatsapp: '962788123456',
      rating: 4.9,
      reviewsCount: 142,
      reviewCount: 142,
      views: 520,
      isVerified: true,
      isFeatured: true,
      packagePlan: 'vip',
      imageUrl: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&q=80&w=800',
      image: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&q=80&w=800',
      createdAt: Date.now() - 86400000 * 10
    },
    {
      isDemo: true,
      name: 'مطعم ومشاوي عروس الشمال',
      category: 'مطاعم ومقاهي',
      description: 'أجود أنواع المشاوي الشامية والكباب والوجبات العائلية بأسعار شعبية ومكونات طازجة يومياً.',
      address: 'شارع الثلاثين، بالقرب من دوار الثقافة، إربد',
      phone: '0777345678',
      whatsapp: '962777345678',
      rating: 4.7,
      reviewsCount: 98,
      reviewCount: 98,
      views: 310,
      isVerified: true,
      isFeatured: true,
      packagePlan: 'golden',
      imageUrl: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?auto=format&fit=crop&q=80&w=800',
      image: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?auto=format&fit=crop&q=80&w=800',
      createdAt: Date.now() - 86400000 * 9
    },
    {
      isDemo: true,
      name: 'حلويات حبيبة وشفا إربد',
      category: 'حلويات ومخابز',
      description: 'أشهر الحلويات الشرقية، كنافة نابلسية بالجبن البلدي، بقلاوة وفطائر طازجة يومياً.',
      address: 'شارع الهاشمي، وسط البلد، إربد',
      phone: '0799887766',
      whatsapp: '962799887766',
      rating: 4.8,
      reviewsCount: 210,
      reviewCount: 210,
      views: 640,
      isVerified: true,
      isFeatured: true,
      packagePlan: 'vip',
      imageUrl: 'https://images.unsplash.com/photo-1587314168485-3236d6710814?auto=format&fit=crop&q=80&w=800',
      image: 'https://images.unsplash.com/photo-1587314168485-3236d6710814?auto=format&fit=crop&q=80&w=800',
      createdAt: Date.now() - 86400000 * 8
    },
    {
      isDemo: true,
      name: 'بيتزا روما الإيطالية (Roma Pizza)',
      category: 'مطاعم ومقاهي',
      description: 'بيتزا إيطالية مخبوزة على حطب الزيتون مع أفضل أشكال العجائن الرقيقة والعروض العائلية.',
      address: 'شارع الجامعة، قرب إشارة الإسكان، إربد',
      phone: '0785544332',
      whatsapp: '962785544332',
      rating: 4.6,
      reviewsCount: 88,
      reviewCount: 88,
      views: 290,
      isVerified: true,
      isFeatured: false,
      packagePlan: 'golden',
      imageUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&q=80&w=800',
      image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&q=80&w=800',
      createdAt: Date.now() - 86400000 * 8
    },
    {
      isDemo: true,
      name: 'محل جالاكسي للخلويات والإلكترونيات',
      category: 'إلكترونيات وهواتف',
      description: 'بيع وتصليح جميع أنواع الهواتف الذكية والأجهزة المحمولة وإكسسوارات الأجهزة مع كفالة حقيقية.',
      address: 'إربد سيتي سنتر، الطابق الأول، إربد',
      phone: '0796655443',
      whatsapp: '962796655443',
      rating: 4.5,
      reviewsCount: 64,
      reviewCount: 64,
      views: 180,
      isVerified: true,
      isFeatured: false,
      packagePlan: 'basic',
      imageUrl: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&q=80&w=800',
      image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&q=80&w=800',
      createdAt: Date.now() - 86400000 * 7
    },
    {
      isDemo: true,
      name: 'بوتيك زهرة إربد للأزياء والموضة',
      category: 'أزياء وموضة',
      description: 'أحدث التشكيلات العصرية للملابس النسائية والعبايات الفاخرة وفساتين المناسبات بأسعار منافسة.',
      address: 'شارع السينما، مقابل مجمع الأغوار القديم، إربد',
      phone: '0778899001',
      whatsapp: '962778899001',
      rating: 4.7,
      reviewsCount: 75,
      reviewCount: 75,
      views: 220,
      isVerified: true,
      isFeatured: true,
      packagePlan: 'golden',
      imageUrl: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&q=80&w=800',
      image: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&q=80&w=800',
      createdAt: Date.now() - 86400000 * 7
    },
    {
      isDemo: true,
      name: 'صالون وسبا لوميير للسيدات (Lumiere Spa)',
      category: 'صالونات ومراكز تجميل',
      description: 'عناية كاملة بالبشرة والشعر، قص وتسريح، الميك أب والمساج العلاجي بأحدث التقنيات الأوروبية.',
      address: 'الحي الشرقي، بالقرب من مدارس كينغستون، إربد',
      phone: '0781122334',
      whatsapp: '962781122334',
      rating: 4.9,
      reviewsCount: 112,
      reviewCount: 112,
      views: 390,
      isVerified: true,
      isFeatured: true,
      packagePlan: 'vip',
      imageUrl: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?auto=format&fit=crop&q=80&w=800',
      image: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?auto=format&fit=crop&q=80&w=800',
      createdAt: Date.now() - 86400000 * 6
    },
    {
      isDemo: true,
      name: 'مركز ابن سينا الطبي الشامل',
      category: 'عيادات ومراكز طبية',
      description: 'مركز طبي متكامل يضم عيادات طب عام، أسنان، جلاดยة، ومختبر تحاليل طبية على مدار 24 ساعة.',
      address: 'شارع الحصن، بالقرب من دوار القبة، إربد',
      phone: '0792233445',
      whatsapp: '962792233445',
      rating: 4.8,
      reviewsCount: 156,
      reviewCount: 156,
      views: 480,
      isVerified: true,
      isFeatured: false,
      packagePlan: 'golden',
      imageUrl: 'https://images.unsplash.com/photo-1629909613654-28e377c37b09?auto=format&fit=crop&q=80&w=800',
      image: 'https://images.unsplash.com/photo-1629909613654-28e377c37b09?auto=format&fit=crop&q=80&w=800',
      createdAt: Date.now() - 86400000 * 6
    },
    {
      isDemo: true,
      name: 'أسواق البركة المركزية',
      category: 'سوبرماركت ومواد غذائية',
      description: 'سوبرماركت شامل لجميع المواد الغذائية، الخضار والفاكهة الطازجة، والمنظفات بأسعار جملة الجملة.',
      address: 'شارع بغداد، قرب مجمع عمان الجديد، إربد',
      phone: '0773344556',
      whatsapp: '962773344556',
      rating: 4.4,
      reviewsCount: 52,
      reviewCount: 52,
      views: 190,
      isVerified: true,
      isFeatured: false,
      packagePlan: 'basic',
      imageUrl: 'https://images.unsplash.com/photo-1578916171728-46686eac8d58?auto=format&fit=crop&q=80&w=800',
      image: 'https://images.unsplash.com/photo-1578916171728-46686eac8d58?auto=format&fit=crop&q=80&w=800',
      createdAt: Date.now() - 86400000 * 5
    },
    {
      isDemo: true,
      name: 'كافيه وتراس جدارا الجبلي',
      category: 'مطاعم ومقاهي',
      description: 'إطلالة بانورامية خلابة على مدينة إربد وسهل حوران، أراجيل مميزة ووجبات خفيفة ومشروبات باردة.',
      address: 'طريق الحصن، مقابل جامعة جدارا، إربد',
      phone: '0784455667',
      whatsapp: '962784455667',
      rating: 4.8,
      reviewsCount: 130,
      reviewCount: 130,
      views: 410,
      isVerified: true,
      isFeatured: true,
      packagePlan: 'vip',
      imageUrl: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&q=80&w=800',
      image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&q=80&w=800',
      createdAt: Date.now() - 86400000 * 5
    },
    {
      isDemo: true,
      name: 'مخابز وأفران النور الأوتوماتيكية',
      category: 'حلويات ومخابز',
      description: 'خبز طازج بجميع أنواعه، خبز عربي وشراك، معجنات وسندويشات ومخبوزات صحية بالشوفان.',
      address: 'حي نزال، بالقرب من مسجد نزال، إربد',
      phone: '0795566778',
      whatsapp: '962795566778',
      rating: 4.6,
      reviewsCount: 84,
      reviewCount: 84,
      views: 260,
      isVerified: true,
      isFeatured: false,
      packagePlan: 'basic',
      imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&q=80&w=800',
      image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&q=80&w=800',
      createdAt: Date.now() - 86400000 * 4
    },
    {
      isDemo: true,
      name: 'مطعم برغر بوكس (Burger Box)',
      category: 'مطاعم ومقاهي',
      description: 'أفضل برغر لحم ودجاج مشوي على الفحم في إربد مع بطاطا الكيرلي وصلصات خاصة متفجرة بالطعم.',
      address: 'شارع الجامعة، بجانب البنك العربي، إربد',
      phone: '0776677889',
      whatsapp: '962776677889',
      rating: 4.7,
      reviewsCount: 95,
      reviewCount: 95,
      views: 340,
      isVerified: true,
      isFeatured: true,
      packagePlan: 'golden',
      imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&q=80&w=800',
      image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&q=80&w=800',
      createdAt: Date.now() - 86400000 * 4
    },
    {
      isDemo: true,
      name: 'صيدلية فارماسي بلس (Pharmacy Plus)',
      category: 'صيدليات ورعاية صحية',
      description: 'صيدلية حديثة توفر جميع الأدوية، مستحضرات التجميل العالمية، والمستلزمات الطبية مع خدمة التوصيل.',
      address: 'شارع الثلاثين، بجانب مستشفى الراهبات الوردية، إربد',
      phone: '0787788990',
      whatsapp: '962787788990',
      rating: 4.9,
      reviewsCount: 67,
      reviewCount: 67,
      views: 210,
      isVerified: true,
      isFeatured: false,
      packagePlan: 'golden',
      imageUrl: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?auto=format&fit=crop&q=80&w=800',
      image: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?auto=format&fit=crop&q=80&w=800',
      createdAt: Date.now() - 86400000 * 3
    },
    {
      isDemo: true,
      name: 'مكتبة وسنتر اليرموك للطباعة والتجليد',
      category: 'مكتبات وخدمات طلابية',
      description: 'طباعة الأبحاث والرسائل الجامعية، تجليد فاخر، تصوير مستندات وملخصات لجميع تخصصات اليرموك.',
      address: 'شارع الجامعة، مقابل البوابة الشرقية، إربد',
      phone: '0798899001',
      whatsapp: '962798899001',
      rating: 4.6,
      reviewsCount: 120,
      reviewCount: 120,
      views: 310,
      isVerified: true,
      isFeatured: false,
      packagePlan: 'basic',
      imageUrl: 'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?auto=format&fit=crop&q=80&w=800',
      image: 'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?auto=format&fit=crop&q=80&w=800',
      createdAt: Date.now() - 86400000 * 3
    },
    {
      isDemo: true,
      name: 'مركز نيو لايف للياقة وكمال الأجسام (New Life Gym)',
      category: 'أندية ورياضة',
      description: 'نادي أجهزة رياضية متطور، مدربين شخصيين، جاكوزي وسونا، واشتراكات خاصة للطلبة والشباب.',
      address: 'شارع فلسطين، بجانب مجمع الباصات القديم، إربد',
      phone: '0779900112',
      whatsapp: '962779900112',
      rating: 4.8,
      reviewsCount: 104,
      reviewCount: 104,
      views: 370,
      isVerified: true,
      isFeatured: true,
      packagePlan: 'vip',
      imageUrl: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&q=80&w=800',
      image: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&q=80&w=800',
      createdAt: Date.now() - 86400000 * 2
    },
    {
      isDemo: true,
      name: 'محل الأناقة الفاخرة للملابس الرجالية',
      category: 'أزياء وموضة',
      description: 'بدلات عريس ورجالية رسمية، قمصان إيطالية وبناطيل سبور، أحدث صيحات الموضة الرجالية.',
      address: 'شارع الهاشمي، بالقرب من دوار الساعة، إربد',
      phone: '0780011223',
      whatsapp: '962780011223',
      rating: 4.5,
      reviewsCount: 48,
      reviewCount: 48,
      views: 170,
      isVerified: true,
      isFeatured: false,
      packagePlan: 'basic',
      imageUrl: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?auto=format&fit=crop&q=80&w=800',
      image: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?auto=format&fit=crop&q=80&w=800',
      createdAt: Date.now() - 86400000 * 2
    },
    {
      isDemo: true,
      name: 'مركز الكابتن لصيانة السيارات والهايبرد',
      category: 'صيانة وسيارات',
      description: 'فحص كمبيوتر أونلاين، صيانة بطاريات الهايبرد والسيارات الكهربائية، تغيير زيت وقطع غيار أصلية.',
      address: 'المنطقة الصناعية، الشارع الرئيسي، إربد',
      phone: '0791122334',
      whatsapp: '962791122334',
      rating: 4.7,
      reviewsCount: 89,
      reviewCount: 89,
      views: 280,
      isVerified: true,
      isFeatured: false,
      packagePlan: 'golden',
      imageUrl: 'https://images.unsplash.com/photo-1486006920555-c77dce18193b?auto=format&fit=crop&q=80&w=800',
      image: 'https://images.unsplash.com/photo-1486006920555-c77dce18193b?auto=format&fit=crop&q=80&w=800',
      createdAt: Date.now() - 86400000 * 1
    },
    {
      isDemo: true,
      name: 'كافيه ديوان زمان الشامي',
      category: 'مطاعم ومقاهي',
      description: 'أجواء شامية تراثية أصيلة، أراجيل، جلسات عائلية هادئة مع مشروبات ساخنة وحلويات شرق وغرب.',
      address: 'شارع الجامعة، بالقرب من دوار الجامعة، إربد',
      phone: '0772233445',
      whatsapp: '962772233445',
      rating: 4.8,
      reviewsCount: 160,
      reviewCount: 160,
      views: 510,
      isVerified: true,
      isFeatured: true,
      packagePlan: 'vip',
      imageUrl: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&q=80&w=800',
      image: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&q=80&w=800',
      createdAt: Date.now() - 86400000 * 1
    },
    {
      isDemo: true,
      name: 'معرض أثاث ومفروشات الشرق',
      category: 'مفروشات وديكور',
      description: 'طقم نوم، غرف معيشة، طاولات سفرة وأثاث مكتبي بأعلى معايير الخشب والمفروشات الفاخرة.',
      address: 'طريق الحصن الرئيسي، بجانب معارض السيارات، إربد',
      phone: '0783344556',
      whatsapp: '962783344556',
      rating: 4.6,
      reviewsCount: 42,
      reviewCount: 42,
      views: 160,
      isVerified: true,
      isFeatured: false,
      packagePlan: 'basic',
      imageUrl: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&q=80&w=800',
      image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&q=80&w=800',
      createdAt: Date.now() - 3600000 * 12
    },
    {
      isDemo: true,
      name: 'استوديو ألوان للتصوير والمونتاج',
      category: 'خدمات وتصوير',
      description: 'تصوير أعراس ومناسبات، تصوير منتجات للمحلات، إعداد فيديوهات إعلانية احترافية ودعايات.',
      address: 'شارع الجامعة، مجمع النجاح الطبقي، إربد',
      phone: '0794455667',
      whatsapp: '962794455667',
      rating: 4.9,
      reviewsCount: 78,
      reviewCount: 78,
      views: 290,
      isVerified: true,
      isFeatured: true,
      packagePlan: 'golden',
      imageUrl: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&q=80&w=800',
      image: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&q=80&w=800',
      createdAt: Date.now() - 3600000 * 6
    }
  ],

  // 20 Housings / Real Estates in Irbid
  housings: [
    {
      isDemo: true,
      title: 'سكن طالبات الزمردة المميز (مقابل اليرموك)',
      type: 'سكن طالبات',
      university: 'اليرموك',
      price: 120,
      pricePeriod: 'شهري',
      location: 'شارع الجامعة - مقابل البوابة الشمالية مباشراً',
      distanceToCampus: '150 متر فقط',
      roomsCount: 'غرف مفردة ومزدوجة',
      services: ['📶 إنترنت ألياف سريع', '⚡ إنفرتر كهرباء', '🧹 تنظيف دوري', '🔐 حراسة وبصمة', '❄️ تكييف مستقل'],
      description: 'سكن طالبات هادئ وآمن جداً ومجهز بالكامل بأرقى الأثاث. مشرفات على مدار 24 ساعة وقريب جداً من المجمعات والكليات.',
      contactPhone: '0788112233',
      contactWhatsapp: '962788112233',
      phone: '0788112233',
      whatsapp: '962788112233',
      ownerName: 'أبو عمر الحوراني',
      image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&q=80&w=800',
      images: ['https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&q=80&w=800'],
      isVerified: true,
      isFeatured: true,
      isVip: true,
      status: 'approved',
      isOccupied: false,
      isAvailable: true,
      viewsCount: 280,
      createdAt: Date.now() - 86400000 * 8
    },
    {
      isDemo: true,
      title: 'شقق النخيل المفروشة للطلاب والشباب',
      type: 'سكن طلاب',
      university: 'اليرموك',
      price: 140,
      pricePeriod: 'شهري',
      location: 'شارع الجامعة - خلف البوابة الشرقية',
      distanceToCampus: '300 متر',
      roomsCount: 'شقة نوم وغرفة معيشة',
      services: ['📶 إنترنت فايبر', '💧 ماء وخدمات مجاناً', '🛋️ مفروش بالكامل', '🧊 ثلاجة وغسالة'],
      description: 'شقق مفروشة حديثة ومستقلة تناسب الطلاب الجامعيين. تشطيبات ديلوكس قريب من المطاعم والخدمات.',
      contactPhone: '0777223344',
      contactWhatsapp: '962777223344',
      phone: '0777223344',
      whatsapp: '962777223344',
      ownerName: 'المهندس خالد العبدالله',
      image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&q=80&w=800',
      images: ['https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&q=80&w=800'],
      isVerified: true,
      isFeatured: true,
      isVip: false,
      status: 'approved',
      isOccupied: false,
      isAvailable: true,
      viewsCount: 190,
      createdAt: Date.now() - 86400000 * 7
    },
    {
      isDemo: true,
      title: 'أستوديو VIP فاخر مستقل للطلاب',
      type: 'أستوديو مفروش',
      university: 'العلوم والتكنولوجيا',
      price: 160,
      pricePeriod: 'شهري',
      location: 'شارع الثلاثين - مقابل موقف تكنو',
      distanceToCampus: 'قريب من موقف الباصات',
      roomsCount: 'أستوديو واسع + مطبخ + حمام',
      services: ['❄️ تكييف حامي بارد', '📶 إنترنت سريع', '📺 شاشة ذكية', '🛗 مصعد مدرج'],
      description: 'أستوديو مفروش حديثاً بأثاث فندقي وفاخر مخصص لطلاب العلوم والتكنولوجيا. موقع حيوية وممتاز.',
      contactPhone: '0799334455',
      contactWhatsapp: '962799334455',
      phone: '0799334455',
      whatsapp: '962799334455',
      ownerName: 'الحاج أبو طارق',
      image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&q=80&w=800',
      images: ['https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&q=80&w=800'],
      isVerified: true,
      isFeatured: true,
      isVip: true,
      status: 'approved',
      isOccupied: false,
      isAvailable: true,
      viewsCount: 310,
      createdAt: Date.now() - 86400000 * 6
    },
    {
      isDemo: true,
      title: 'سكن مريم العائلي للطالبات الجامعيات',
      type: 'سكن طالبات',
      university: 'اليرموك',
      price: 110,
      pricePeriod: 'شهري',
      location: 'شارع الجامعة - قرب إشارة الإسكان',
      distanceToCampus: '250 متر',
      roomsCount: 'غرف مفردة وثنائية',
      services: ['🧹 تنظيف الأروقة', '🔐 نظام كاميرات وحراسة', '📶 إنترنت فايبر', '🔥 تدفئة طابقية'],
      description: 'بيئة هادئة جداً ومناسبة للتحصيل العلمي والدراسة، المشرفة مقيمة في المبنى والأمان عالٍ.',
      contactPhone: '0785566778',
      contactWhatsapp: '962785566778',
      phone: '0785566778',
      whatsapp: '962785566778',
      ownerName: 'أم محمد التميمي',
      image: 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&q=80&w=800',
      images: ['https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&q=80&w=800'],
      isVerified: true,
      isFeatured: false,
      isVip: false,
      status: 'approved',
      isOccupied: false,
      isAvailable: true,
      viewsCount: 150,
      createdAt: Date.now() - 86400000 * 6
    },
    {
      isDemo: true,
      title: 'شقة عائلية سوبر ديلوكس 3 نوم',
      type: 'شقق عائلية',
      university: 'أخرى / وسط المدينة',
      price: 250,
      pricePeriod: 'شهري',
      location: 'الحي الشرقي - بالقرب من مدرسة ثانوية إربد',
      distanceToCampus: '10 دقائق بالسيارة',
      roomsCount: '3 نوم + صالون واسع + 2 حمام',
      services: ['🚗 كراج سيارة مستقل', '🛗 مصعد حديث', '🔥 تدفئة مركزية', '🪵 أرضيات باركيه'],
      description: 'شقة فارغة حديثة البناء في منطقة هادئة وراقية جداً بالقرب من جميع الخدمات والمستشفيات.',
      contactPhone: '0778899112',
      contactWhatsapp: '962778899112',
      phone: '0778899112',
      whatsapp: '962778899112',
      ownerName: 'الدكتور أحمد الشبول',
      image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&q=80&w=800',
      images: ['https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&q=80&w=800'],
      isVerified: true,
      isFeatured: true,
      isVip: false,
      status: 'approved',
      isOccupied: false,
      isAvailable: true,
      viewsCount: 240,
      createdAt: Date.now() - 86400000 * 5
    },
    {
      isDemo: true,
      title: 'سكن الأمير للشباب والطلاب الجامعيين',
      type: 'سكن شباب',
      university: 'العلوم والتكنولوجيا',
      price: 90,
      pricePeriod: 'شهري',
      location: 'شارع الثلاثين - بالقرب من دوار الثقافة',
      distanceToCampus: 'موقع استراتيجي للطلاب',
      roomsCount: 'غرف مزدوجة ومستقلة',
      services: ['📶 إنترنت مجاني', '🧊 مطبخ مشتركة مجهز', '🧺 غسالات كوين', '💧 خدمات شاملة'],
      description: 'سكن شبابي اقتصادي ومريح جداً. تشمل الأجرة الماء والكهرباء والإنترنت بدون أي تكاليف إضافية.',
      contactPhone: '0791133557',
      contactWhatsapp: '962791133557',
      phone: '0791133557',
      whatsapp: '962791133557',
      ownerName: 'أبو قصي البطاينة',
      image: 'https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?auto=format&fit=crop&q=80&w=800',
      images: ['https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?auto=format&fit=crop&q=80&w=800'],
      isVerified: true,
      isFeatured: false,
      isVip: false,
      status: 'approved',
      isOccupied: false,
      isAvailable: true,
      viewsCount: 170,
      createdAt: Date.now() - 86400000 * 5
    },
    {
      isDemo: true,
      title: 'أستوديو حديث مفروش بالكامل (شارع الجامعة)',
      type: 'أستوديو مفروش',
      university: 'اليرموك',
      price: 130,
      pricePeriod: 'شهري',
      location: 'شارع الجامعة - خلف كليات الاقتصاد',
      distanceToCampus: '200 متر walking distance',
      roomsCount: 'أستوديو غرفة ومطبخ أمريكي',
      services: ['❄️ مكيف حامي بارد', '📺 شاشة LCD', '📶 إنترنت ألياف', '💧 الماي مجاناً'],
      description: 'أستوديو مميز جداً بأثاث جديد بالكامل مع إضاءة LED وموقع ممتاز خلف الكليات الكبيرة مباشرة.',
      contactPhone: '0782244668',
      contactWhatsapp: '962782244668',
      phone: '0782244668',
      whatsapp: '962782244668',
      ownerName: 'الاستاذ سامر عبيدات',
      image: 'https://images.unsplash.com/photo-1502005229762-cf1b2da7c5d6?auto=format&fit=crop&q=80&w=800',
      images: ['https://images.unsplash.com/photo-1502005229762-cf1b2da7c5d6?auto=format&fit=crop&q=80&w=800'],
      isVerified: true,
      isFeatured: true,
      isVip: true,
      status: 'approved',
      isOccupied: false,
      isAvailable: true,
      viewsCount: 290,
      createdAt: Date.now() - 86400000 * 4
    },
    {
      isDemo: true,
      title: 'سكن طالبات ياسمين الشام (البوابة الغربية)',
      type: 'سكن طالبات',
      university: 'اليرموك',
      price: 125,
      pricePeriod: 'شهري',
      location: 'شارع الجامعة - مقابل البوابة الغربية',
      distanceToCampus: '100 متر فقط',
      roomsCount: 'غرف سرير وسريرين',
      services: ['🔐 حراسة وأمان 24/7', '📶 فايبر سريع', '❄️ مكيفات سبليت', '🧹 صيانة مستمرة'],
      description: 'من أرقى سكنات الطالبات في إربد، هدوء تام وإشراف عالي المستوى ومبنى مؤمن بالكاميرات والكهرباء.',
      contactPhone: '0773355779',
      contactWhatsapp: '962773355779',
      phone: '0773355779',
      whatsapp: '962773355779',
      ownerName: 'أم حمزة الشامية',
      image: 'https://images.unsplash.com/photo-1540518614846-7eded433c457?auto=format&fit=crop&q=80&w=800',
      images: ['https://images.unsplash.com/photo-1540518614846-7eded433c457?auto=format&fit=crop&q=80&w=800'],
      isVerified: true,
      isFeatured: false,
      isVip: false,
      status: 'approved',
      isOccupied: false,
      isAvailable: true,
      viewsCount: 200,
      createdAt: Date.now() - 86400000 * 4
    },
    {
      isDemo: true,
      title: 'شقة طلابية مفروشة 2 نوم سوبر ديلوكس',
      type: 'سكن طلاب',
      university: 'العلوم والتكنولوجيا',
      price: 180,
      pricePeriod: 'شهري',
      location: 'شارع الجامعة - بالقرب من سيتي سنتر',
      distanceToCampus: 'موقع حيوي ممتاز',
      roomsCount: '2 نوم + صالة واسعة',
      services: ['🛋️ أثاث زيرو حديث', '📶 إنترنت متصل', '❄️ تكييف بكل غرفة', '🚗 مواقف متوفرة'],
      description: 'شقة طلابية راقية ومناسبة لـ 2 أو 3 طلاب من العلوم والتكنولوجيا، أثاث كامل مع غسالة أوتوماتيك وثلاجة كبيرة.',
      contactPhone: '0794466880',
      contactWhatsapp: '962794466880',
      phone: '0794466880',
      whatsapp: '962794466880',
      ownerName: 'السيد محمود طلافحة',
      image: 'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&q=80&w=800',
      images: ['https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&q=80&w=800'],
      isVerified: true,
      isFeatured: true,
      isVip: false,
      status: 'approved',
      isOccupied: false,
      isAvailable: true,
      viewsCount: 230,
      createdAt: Date.now() - 86400000 * 3
    },
    {
      isDemo: true,
      title: 'جناح فندقي مفروش للطلاب قرب جامعة جدارا',
      type: 'أستوديو مفروش',
      university: 'جدارا',
      price: 150,
      pricePeriod: 'شهري',
      location: 'طريق الحصن - قرب كليات جامعة جدارا',
      distanceToCampus: 'مباشرة مقابل الكليات',
      roomsCount: 'جناح فندقي متكامل',
      services: ['📶 فايبر 500 ميجا', '🧹 خدمة تنظيف أسبوعية', '❄️ تكييف', '☕ بوفيه إفطار اختياري'],
      description: 'أجنحة فندقية مفروشة ومصممة خصيصاً لراحة طلاب الجامعات بالقرب من جامعة جدارا والجامعة الأهلية.',
      contactPhone: '0785577991',
      contactWhatsapp: '962785577991',
      phone: '0785577991',
      whatsapp: '962785577991',
      ownerName: 'إدارة أجنحة جدارا الفندقية',
      image: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&q=80&w=800',
      images: ['https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&q=80&w=800'],
      isVerified: true,
      isFeatured: false,
      isVip: true,
      status: 'approved',
      isOccupied: false,
      isAvailable: true,
      viewsCount: 160,
      createdAt: Date.now() - 86400000 * 3
    },
    {
      isDemo: true,
      title: 'سكن أركان للطلاب الجامعيين (اقتصادي)',
      type: 'سكن طلاب',
      university: 'اليرموك',
      price: 100,
      pricePeriod: 'شهري',
      location: 'شارع الجامعة - قرب البوابة الشمالية',
      distanceToCampus: '200 متر',
      roomsCount: 'غرف مفردة ومزدوجة',
      services: ['📶 إنترنت مجاني', '💧 ماء وكهرباء مشمولة', '🧊 مطبخ مجهز', '🧹 صيانة مستمرة'],
      description: 'سكن شبابي هادئ ومناسب جداً للطلاب الراغبين في سكن اقتصادي قريب من الكليات والمكتبة.',
      contactPhone: '0776688002',
      contactWhatsapp: '962776688002',
      phone: '0776688002',
      whatsapp: '962776688002',
      ownerName: 'أبو فيصل الزعبي',
      image: 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&q=80&w=800',
      images: ['https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&q=80&w=800'],
      isVerified: true,
      isFeatured: false,
      isVip: false,
      status: 'approved',
      isOccupied: false,
      isAvailable: true,
      viewsCount: 140,
      createdAt: Date.now() - 86400000 * 2
    },
    {
      isDemo: true,
      title: 'شقة عائلية أرضية مع حديقة ومدخل مستقل',
      type: 'شقق عائلية',
      university: 'أخرى / وسط المدينة',
      price: 220,
      pricePeriod: 'شهري',
      location: 'شارع الهاشمي - بالقرب من المستشفى التخصصي',
      distanceToCampus: 'وسط المدينة',
      roomsCount: '2 نوم + صالة + حديقة صغيرة',
      services: ['🌳 حديقة منزلية', '🚗 كراج سيارة', '💧 خزان ماء كبير', '🪵 تشطيب حديث'],
      description: 'شقة أرضية بمدخل خاص وحديقة صغيرة مجهزة للعائلات الهادئة بالقرب من الأسواق والمستشفيات.',
      contactPhone: '0797799113',
      contactWhatsapp: '962797799113',
      phone: '0797799113',
      whatsapp: '962797799113',
      ownerName: 'المحامي يوسف العزام',
      image: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&q=80&w=800',
      images: ['https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&q=80&w=800'],
      isVerified: true,
      isFeatured: true,
      isVip: false,
      status: 'approved',
      isOccupied: false,
      isAvailable: true,
      viewsCount: 260,
      createdAt: Date.now() - 86400000 * 2
    },
    {
      isDemo: true,
      title: 'سكن طالبات الفردوس الأنيق (موقف تكنو)',
      type: 'سكن طالبات',
      university: 'العلوم والتكنولوجيا',
      price: 135,
      pricePeriod: 'شهري',
      location: 'شارع الثلاثين - مقابل مجمع تكنو مباشرة',
      distanceToCampus: 'دقيقة واحدة من موقف الباصات',
      roomsCount: 'أستوديو وغرف واسعة',
      services: ['🔐 حراسة أمنية متكاملة', '📶 إنترنت سريع', '⚡ مولد كهرباء احتياطي', '❄️ تكييف'],
      description: 'مبنى سكن طالبات فخم وجديد، خدمة مواصلات مؤمنة للمجمع وإشراف نسائي متواصل على مدار اليوم.',
      contactPhone: '0788800224',
      contactWhatsapp: '962788800224',
      phone: '0788800224',
      whatsapp: '962788800224',
      ownerName: 'أم يزن الكردي',
      image: 'https://images.unsplash.com/photo-1567496898669-ee935f5f647a?auto=format&fit=crop&q=80&w=800',
      images: ['https://images.unsplash.com/photo-1567496898669-ee935f5f647a?auto=format&fit=crop&q=80&w=800'],
      isVerified: true,
      isFeatured: true,
      isVip: true,
      status: 'approved',
      isOccupied: false,
      isAvailable: true,
      viewsCount: 270,
      createdAt: Date.now() - 86400000 * 1
    },
    {
      isDemo: true,
      title: 'أستوديو مفروش اقتصادي للطلاب',
      type: 'أستوديو مفروش',
      university: 'اليرموك',
      price: 95,
      pricePeriod: 'شهري',
      location: 'شارع الحصن - بالقرب من دوار القبة',
      distanceToCampus: '5 دقائق بالباص',
      roomsCount: 'أستوديو غرفة ومنافعها',
      services: ['📶 إنترنت مجاني', '🛋️ مفروش بسرير ومكتب', '💧 ماء وكهرباء مجاناً'],
      description: 'أستوديو مفروش وبسعر اقتصادي جداً يناسب الطلاب الراغبين بشرط هدوء وأسعار مناسبة.',
      contactPhone: '0779911335',
      contactWhatsapp: '962779911335',
      phone: '0779911335',
      whatsapp: '962779911335',
      ownerName: 'السيد وائل بني هاني',
      image: 'https://images.unsplash.com/photo-1536376072261-38c75010e6c9?auto=format&fit=crop&q=80&w=800',
      images: ['https://images.unsplash.com/photo-1536376072261-38c75010e6c9?auto=format&fit=crop&q=80&w=800'],
      isVerified: true,
      isFeatured: false,
      isVip: false,
      status: 'approved',
      isOccupied: false,
      isAvailable: true,
      viewsCount: 130,
      createdAt: Date.now() - 86400000 * 1
    },
    {
      isDemo: true,
      title: 'سكن الأمل للطالبات الجامعيات (شارع الجامعة)',
      type: 'سكن طالبات',
      university: 'اليرموك',
      price: 115,
      pricePeriod: 'شهري',
      location: 'شارع الجامعة - قرب مطعم كتاكيت',
      distanceToCampus: '180 متر',
      roomsCount: 'غرف فردية ومفروشة',
      services: ['📶 إنترنت فايبر', '🧹 تنظيف يومي للمرافق', '🔐 دخول كرت ذكي', '❄️ مكيف'],
      description: 'سكن نظيف ومريح جداً مع مطبخ كبير مشترك وأجواء هادئة تسودها المودة بين الطالبات.',
      contactPhone: '0790022446',
      contactWhatsapp: '962790022446',
      phone: '0790022446',
      whatsapp: '962790022446',
      ownerName: 'أم خالد الروسان',
      image: 'https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&q=80&w=800',
      images: ['https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&q=80&w=800'],
      isVerified: true,
      isFeatured: false,
      isVip: false,
      status: 'approved',
      isOccupied: false,
      isAvailable: true,
      viewsCount: 180,
      createdAt: Date.now() - 3600000 * 18
    },
    {
      isDemo: true,
      title: 'شقة مفروشة 3 غرف نوم لطلاب اليرموك',
      type: 'سكن طلاب',
      university: 'اليرموك',
      price: 210,
      pricePeriod: 'شهري',
      location: 'شارع الجامعة - بالقرب من البوابة الشرقية',
      distanceToCampus: '250 متر',
      roomsCount: '3 نوم + صالة واسعة',
      services: ['🛋️ مفروشة بالكامل', '📶 إنترنت سريع', '🧊 ثلاجة وغسالة', '❄️ مكيف بكل غرفة'],
      description: 'شقة واسعة ومريحة لثلاثة أو أربعة طلاب مع صالة تلفزيون ومطبخ متكامل بالكامل.',
      contactPhone: '0781133557',
      contactWhatsapp: '962781133557',
      phone: '0781133557',
      whatsapp: '962781133557',
      ownerName: 'المهندس رامي المقدادي',
      image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&q=80&w=800',
      images: ['https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&q=80&w=800'],
      isVerified: true,
      isFeatured: true,
      isVip: false,
      status: 'approved',
      isOccupied: false,
      isAvailable: true,
      viewsCount: 220,
      createdAt: Date.now() - 3600000 * 14
    },
    {
      isDemo: true,
      title: 'سكن الرحمة الهادئ للطالبات (قرب جدارا)',
      type: 'سكن طالبات',
      university: 'جدارا',
      price: 105,
      pricePeriod: 'شهري',
      location: 'طريق الحصن - قرب كليات جامعة جدارا',
      distanceToCampus: '300 متر',
      roomsCount: 'غرف مفردة وثنائية',
      services: ['📶 إنترنت مجاني', '🔐 حراسة نسائية', '🧹 تنظيف مستمر', '💧 خدمات مشمولة'],
      description: 'سكن مخصص لطالبات جامعة جدارا ومحيطها، هدوء تام ورعاية شاملة وأسعار مناسبة جداً.',
      contactPhone: '0772244668',
      contactWhatsapp: '962772244668',
      phone: '0772244668',
      whatsapp: '962772244668',
      ownerName: 'أم سارة المحاسنة',
      image: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&q=80&w=800',
      images: ['https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&q=80&w=800'],
      isVerified: true,
      isFeatured: false,
      isVip: false,
      status: 'approved',
      isOccupied: false,
      isAvailable: true,
      viewsCount: 120,
      createdAt: Date.now() - 3600000 * 10
    },
    {
      isDemo: true,
      title: 'شقة عائلية مفروشة لوكس - حي نزال',
      type: 'شقق عائلية',
      university: 'أخرى / وسط المدينة',
      price: 280,
      pricePeriod: 'شهري',
      location: 'حي نزال - الشارع العام',
      distanceToCampus: 'وسط المدينة',
      roomsCount: '3 نوم + صالة ضيوف + 2 حمام',
      services: ['🛋️ مفروشة بأثاث فاخر', '🛗 مصعد مدرج', '🚗 مواقف كراج', '❄️ مكيفات'],
      description: 'شقة مفروشة بالكامل جاهزة للسكن الفوري للعائلات أو المغتربين، موقع هادئ جداً ومخدوم.',
      contactPhone: '0793355779',
      contactWhatsapp: '962793355779',
      phone: '0793355779',
      whatsapp: '962793355779',
      ownerName: 'أبو خلدون عبيدات',
      image: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&q=80&w=800',
      images: ['https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&q=80&w=800'],
      isVerified: true,
      isFeatured: true,
      isVip: false,
      status: 'approved',
      isOccupied: false,
      isAvailable: true,
      viewsCount: 250,
      createdAt: Date.now() - 3600000 * 8
    },
    {
      isDemo: true,
      title: 'غرف مفردة مفروشة للطلاب (شارع الثلاثين)',
      type: 'غرفة مفردة',
      university: 'العلوم والتكنولوجيا',
      price: 85,
      pricePeriod: 'شهري',
      location: 'شارع الثلاثين - قرب دوار الثقافة',
      distanceToCampus: 'موقع حيوي ممتاز',
      roomsCount: 'غرفة خاصة مع منافع مشتركة',
      services: ['📶 إنترنت مجاني', '🧊 ثلاجة ومطبخ مشترك', '💧 ماء وكهرباء مشمولة'],
      description: 'غرف مستقلة ومفروشة بأسعار اقتصادية ممتازة للطلاب الراغبين بالغرف الفردية الهادئة.',
      contactPhone: '0784466880',
      contactWhatsapp: '962784466880',
      phone: '0784466880',
      whatsapp: '962784466880',
      ownerName: 'أبو معاذ العوملة',
      image: 'https://images.unsplash.com/photo-1598928506311-c55ded91a20c?auto=format&fit=crop&q=80&w=800',
      images: ['https://images.unsplash.com/photo-1598928506311-c55ded91a20c?auto=format&fit=crop&q=80&w=800'],
      isVerified: true,
      isFeatured: false,
      isVip: false,
      status: 'approved',
      isOccupied: false,
      isAvailable: true,
      viewsCount: 160,
      createdAt: Date.now() - 3600000 * 5
    },
    {
      isDemo: true,
      title: 'سكن اليرموك الذهبي للطالبات (البوابة الشمالية)',
      type: 'سكن طالبات',
      university: 'اليرموك',
      price: 145,
      pricePeriod: 'شهري',
      location: 'شارع الجامعة - ملاصق للبوابة الشمالية',
      distanceToCampus: '50 متر فقط',
      roomsCount: 'أستوديو وغرف فاخرة',
      services: ['🔐 أمان وبصمة وجه', '❄️ تكييف مركزي', '📶 إنترنت فايبر مجاناً', '🧹 تنظيف يومي'],
      description: 'أفخم سكن طالبات في المنطقة، أمان عالي جداً وتكييف وموقع لا يبعد سوى خطوات عن الجامعة.',
      contactPhone: '0775577991',
      contactWhatsapp: '962775577991',
      phone: '0775577991',
      whatsapp: '962775577991',
      ownerName: 'أم ليث الجراح',
      image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=800',
      images: ['https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=800'],
      isVerified: true,
      isFeatured: true,
      isVip: true,
      status: 'approved',
      isOccupied: false,
      isAvailable: true,
      viewsCount: 340,
      createdAt: Date.now() - 3600000 * 2
    }
  ],

  // 20 Job Listings in Irbid
  jobs: [
    {
      isDemo: true,
      title: 'باريستا ومعد مشروبات مختصة',
      company: 'كافيه لافا (Lava Specialty Coffee)',
      category: 'مطاعم ومقاهي',
      jobType: 'دوام كامل',
      location: 'شارع الجامعة، مقابل البوابة الشمالية لليرموك',
      salary: '320 - 380 دينار + إكراميات',
      workHours: 'شفت 8 ساعات (صباحي أو مسائي)',
      experienceLevel: 'خبرة سنة على الأقل',
      genderPreference: 'all',
      benefits: ['🍔 وجبة طعام يومية مجانية', '🎉 إكراميات يومية', '✨ تدريب مدفوع'],
      description: 'مطلوب باريستا محترف لديه خبرة في إعداد القهوة المختصة واللاتيه آرت وإدارة محطة العمل بسرعة واحترافية.',
      requirements: ['خبرة لا تقل عن سنة', 'إتقان الرسم على القهوة', 'اللباقة وحسن الاستقبال'],
      howToApply: 'إرسال السيرة الذاتية أو أعمال اللاتيه آرت عبر الواتساب',
      contactPhone: '0788123456',
      contactWhatsapp: '962788123456',
      isUrgent: true,
      status: 'active',
      createdAt: Date.now() - 3600000 * 4
    },
    {
      isDemo: true,
      title: 'موظف مبيعات وتسويق إلكتروني (مناسب للطلاب)',
      company: 'مجموعة النجوم للتجارة والإلكترونيات',
      category: 'تسويق وتكنولوجيا',
      jobType: 'مناسب للطلاب',
      location: 'إربد سيتي سنتر، الطابق الثاني',
      salary: '280 دينار + عمولات مبيعات مجزية',
      workHours: 'ساعات مرنة متوافقة مع أوقات المحاضرات',
      experienceLevel: 'بدون خبرة (مرحب بالخريجين والطلبة)',
      genderPreference: 'all',
      benefits: ['💰 عمولات مبيعات', '🎓 ساعات مرنة تتناسب مع الدراسة'],
      description: 'نبحث عن شاب أو شابة بشغف للتسويق الرقمي والمبيعات للرد على استفسارات الزبائن على مواقع التواصل.',
      requirements: ['طالب جامعي أو خريج جديد', 'مهارة عالية في التواصل', 'ساعات عمل مرنة'],
      howToApply: 'التقديم عبر الواتساب مع ذكر التخصص والجامعة',
      contactPhone: '0799654321',
      contactWhatsapp: '962799654321',
      isUrgent: true,
      status: 'active',
      createdAt: Date.now() - 3600000 * 12
    },
    {
      isDemo: true,
      title: 'شيف وجبات سريعة وبرغر على الفحم',
      company: 'مطعم برغر بوكس (Burger Box)',
      category: 'مطاعم ومقاهي',
      jobType: 'دوام كامل',
      location: 'شارع الجامعة - إربد',
      salary: '350 - 420 دينار',
      workHours: 'شفت مسائي 8 ساعات',
      experienceLevel: 'خبرة 2-4 سنوات',
      genderPreference: 'males',
      benefits: ['🍔 وجبات طعام', '🚗 بدل مواصلات', '✨ حوافز أداء'],
      description: 'مطلوب شيف متمرس في تجهيز البرغر والصلصات الخاصة وإدارة خط الشواء على الفحم بدقة عالية.',
      requirements: ['خبرة سابقة بمطاعم البرغر', 'الالتزام بمعايير النظافة والجودة', 'سرعة الإنجاز'],
      howToApply: 'الاتصال المباشر أو التقديم عبر الواتساب',
      contactPhone: '0776677889',
      contactWhatsapp: '962776677889',
      isUrgent: true,
      status: 'active',
      createdAt: Date.now() - 3600000 * 8
    },
    {
      isDemo: true,
      title: 'كاشير وموظف استقبال (دوام مسائي)',
      company: 'مطعم ومشاوي عروس الشمال',
      category: 'مطاعم ومقاهي',
      jobType: 'دوام كامل',
      location: 'شارع الثلاثين - إربد',
      salary: '300 - 330 دينار',
      workHours: '4:00 عصراً حتى 12:00 ليلاً',
      experienceLevel: 'خبرة سنة على الأقل',
      genderPreference: 'males',
      benefits: ['🍔 وجبة عشاء مجانية', '🎉 إكراميات أسبوعية'],
      description: 'مطلوب موظف كاشير لاستلام الطلبات وحساب الصندوق والرد على مكالمات الزبائن وتنسيق الطلبات الخارجية.',
      requirements: ['إتقان برامج المحاسبة والكاشير', 'حسن المظهر وحسن التعامل', 'الأمانة والدقة'],
      howToApply: 'الزيارة المباشرة للمطعم أو التواصل عبر الهاتف',
      contactPhone: '0777345678',
      contactWhatsapp: '962777345678',
      isUrgent: false,
      status: 'active',
      createdAt: Date.now() - 3600000 * 16
    },
    {
      isDemo: true,
      title: 'معلم حلويات شرقية وكنافة نابلسية',
      company: 'حلويات حبيبة وشفا إربد',
      category: 'حلويات ومخابز',
      jobType: 'دوام كامل',
      location: 'شارع الهاشمي - وسط البلد، إربد',
      salary: '420 - 500 دينار (حسب الخبرة)',
      workHours: '8 ساعات يومياً',
      experienceLevel: 'خبرة من 3 إلى 5 سنوات',
      genderPreference: 'males',
      benefits: ['💰 راتب مجزي جداً', '🍔 وجبة طعام', '✨ تأمين صحي'],
      description: 'مطلوب معلم كنافة وحلويات شرقية لتجهيز القطر والعجين والكنافة النابلسية بدقة عالية ورونق شرقي.',
      requirements: ['خبرة مؤكدة في مجال الحلويات الشرقية', 'إتقان صبات الكنافة والبقلاوة', 'سرعة العمل'],
      howToApply: 'الاتصال المباشر مع إدارة الحلويات',
      contactPhone: '0799887766',
      contactWhatsapp: '962799887766',
      isUrgent: true,
      status: 'active',
      createdAt: Date.now() - 3600000 * 20
    },
    {
      isDemo: true,
      title: 'فني صيانة خلويات وهواتف ذكية',
      company: 'محل جالاكسي للخلويات',
      category: 'إلكترونيات وهواتف',
      jobType: 'دوام كامل',
      location: 'إربد سيتي سنتر',
      salary: '350 - 450 دينار + نسبة على الصيانة',
      workHours: '10:00 صباحاً حتى 7:00 مساءً',
      experienceLevel: 'خبرة سنتين على الأقل',
      genderPreference: 'males',
      benefits: ['💰 نسبة مجزية من كل جهاز صيانة', '✨ بيئة عمل مريحة ومكيفة'],
      description: 'مطلوب فني هاردوير وسوفتوير معتمد لصيانة أجهزة الآيفون والأندرويد وتغيير الشاشات والآيسيات.',
      requirements: ['إتقان لحام المايكرو والصيانة الدقيقة', 'معرفة ممتازة بأجهزة الأبل والسامسونج'],
      howToApply: 'إرسال السيرة الذاتية عبر الواتساب',
      contactPhone: '0796655443',
      contactWhatsapp: '962796655443',
      isUrgent: false,
      status: 'active',
      createdAt: Date.now() - 86400000 * 1
    },
    {
      isDemo: true,
      title: 'موظفة مبيعات ملابس وأزياء نسائية',
      company: 'بوتيك زهرة إربد للأزياء',
      category: 'أزياء وموضة',
      jobType: 'دوام كامل',
      location: 'شارع السينما - إربد',
      salary: '290 - 320 دينار + عمولات مبيعات',
      workHours: '10:00 صباحاً حتى 6:00 مساءً',
      experienceLevel: 'خبرة سنة في المبيعات',
      genderPreference: 'females',
      benefits: ['💰 عمولة على التارغت الشهري', '🎉 خصم خاص للإنتاج'],
      description: 'نبحث عن فتاة بأسلوب راقٍ ولبق لمساعدة الزبائن في اختيار الملابس وتنسيق الألوان وإدارة المبيعات.',
      requirements: ['اللباقة وحسن الاستقبال', 'الاهتمام بالمظهر العام', 'الخبرة في ترتيب المعرض'],
      howToApply: 'المقابلة الشفهية بالبوتيك مباشرة أو عبر الواتساب',
      contactPhone: '0778899001',
      contactWhatsapp: '962778899001',
      isUrgent: false,
      status: 'active',
      createdAt: Date.now() - 86400000 * 1
    },
    {
      isDemo: true,
      title: 'كوافير وأخصائية شعر وتجميل',
      company: 'صالون وسبا لوميير للسيدات',
      category: 'صالونات ومراكز تجميل',
      jobType: 'دوام كامل',
      location: 'الحي الشرقي - إربد',
      salary: '350 - 450 دينار + نسب مجزية',
      workHours: '10:00 صباحاً حتى 7:00 مساءً',
      experienceLevel: 'خبرة لا تقل عن 3 سنوات',
      genderPreference: 'females',
      benefits: ['💰 نسب مجزية على الخدمات', '✨ مواصلات تأمين'],
      description: 'مطلوب أخصائية شعر متمرسة في السشوار والصبغات والبروتين والتساريح وميك أب المناسبات.',
      requirements: ['إتقان كافة خدمات الشعر والصبغات', 'الالتزام بالنظافة والتعقيم', 'المظهر اللبق'],
      howToApply: 'إرسال صور أو فيديوهات للعمل السابق عبر الواتساب',
      contactPhone: '0781122334',
      contactWhatsapp: '962781122334',
      isUrgent: true,
      status: 'active',
      createdAt: Date.now() - 86400000 * 2
    },
    {
      isDemo: true,
      title: 'ممرض / ممرضة قانونية للعيادات الطبقية',
      company: 'مركز ابن سينا الطبي الشامل',
      category: 'عيادات ومراكز طبية',
      jobType: 'دوام كامل',
      location: 'شارع الحصن - إربد',
      salary: '380 - 430 دينار',
      workHours: 'شفتات متغيرات (صباحي / مسائي)',
      experienceLevel: 'خبرة سنة على الأقل + مزاولة مهنة',
      genderPreference: 'all',
      benefits: ['✨ تأمين صحي شامل', '🎉 ضمان اجتماعي'],
      description: 'مطلوب ممرض/ممرضة قانونية للعمل في قسم الطوارئ وسحب العينات وإعطاء المغذيات بالمركز.',
      requirements: ['شهادة تمريض قانوني + مزاولة مهنة', 'إتقان سحب الدم وتخبيط الوريد بسرعة', 'حسن التعامل'],
      howToApply: 'تقديم السيرة الذاتية لإدارة المركز الطبي',
      contactPhone: '0792233445',
      contactWhatsapp: '962792233445',
      isUrgent: false,
      status: 'active',
      createdAt: Date.now() - 86400000 * 2
    },
    {
      isDemo: true,
      title: 'موظف ترتيب وتنظيم رفوف ومبيعات',
      company: 'أسواق البركة المركزية',
      category: 'سوبرماركت ومواد غذائية',
      jobType: 'دوام كامل',
      location: 'شارع بغداد - إربد',
      salary: '280 - 310 دينار',
      workHours: '8 ساعات (صباحي من 8 إلى 4)',
      experienceLevel: 'مرحب بالبدون خبرة',
      genderPreference: 'males',
      benefits: ['🍔 وجبة إفطار', '🎉 زيادة سنوية'],
      description: 'مطلوب شاب نشيط لترتيب البضائع على الرفوف وتدقيق صلاحيات المنتجات وتلبية طلبات الزبائن.',
      requirements: ['اللياقة والنشاط والالتزام بالوقت', 'الأمانة في التعامل'],
      howToApply: 'التواصل الفوري عبر الهاتف',
      contactPhone: '0773344556',
      contactWhatsapp: '962773344556',
      isUrgent: false,
      status: 'active',
      createdAt: Date.now() - 86400000 * 3
    },
    {
      isDemo: true,
      title: 'صيدلي / صيدلانية (دوام جزئي مسائي)',
      company: 'صيدلية فارماسي بلس',
      category: 'صيدليات ورعاية صحية',
      jobType: 'دوام جزئي',
      location: 'شارع الثلاثين - إربد',
      salary: '300 - 350 دينار',
      workHours: 'من 5:00 مساءً حتى 11:00 ليلاً',
      experienceLevel: 'ترخيص مزاولة مهنة صيدلة',
      genderPreference: 'all',
      benefits: ['✨ بيئة عمل راقية ومكيفة', '🎉 خصم على المستحضرات'],
      description: 'مطلوب صيدلي/صيدلانية لإدارة الصيدلية بالشفت المسائي والرد على استفسارات الأدوية وخدمة الزبائن.',
      requirements: ['بكالوريوس صيدلة + ترخيص مزاولة', 'معرفة بدائل الأدوية ومستحضرات التجميل'],
      howToApply: 'إرسال السيرة الذاتية عبر البريد أو الواتساب',
      contactPhone: '0787788990',
      contactWhatsapp: '962787788990',
      isUrgent: true,
      status: 'active',
      createdAt: Date.now() - 86400000 * 3
    },
    {
      isDemo: true,
      title: 'سائق توصيل طلبات (دراجة أو سيارة خاصة)',
      company: 'مطعم بيتزا روما الإيطالية',
      category: 'توصيل وخدمات',
      jobType: 'دوام كامل',
      location: 'شارع الجامعة - إربد',
      salary: '350 دينار + بدل بنزين + إكراميات',
      workHours: 'من 12:00 ظهراً حتى 8:00 مساءً',
      experienceLevel: 'رخصة قيادة سارية المفعول',
      genderPreference: 'males',
      benefits: ['🍔 وجبة بيتزا يومية', '⛽ بدل بنزين يومي'],
      description: 'مطلوب سائق لتوصيل طلبات البيتزا إلى منازل وسكنات الطلاب في مختلف مناطق إربد بدقة وسرعة.',
      requirements: ['امتلاك دراجة نارية أو سيارة اقتصادية', 'معرفة ممتازة بأحياء وشوارع إربد'],
      howToApply: 'الاتصال المباشر لإتمام المقابلة',
      contactPhone: '0785544332',
      contactWhatsapp: '962785544332',
      isUrgent: true,
      status: 'active',
      createdAt: Date.now() - 86400000 * 4
    },
    {
      isDemo: true,
      title: 'مصمم جرافيكي ومحرر فيديوهات قصيرة',
      company: 'استوديو ألوان للتصوير والإنتاج',
      category: 'تصميم وإعلام',
      jobType: 'دوام كامل',
      location: 'شارع الجامعة - إربد',
      salary: '350 - 420 دينار',
      workHours: '9:00 صباحاً حتى 5:00 مساءً',
      experienceLevel: 'خبرة سنتين في المونتاج والتصميم',
      genderPreference: 'all',
      benefits: ['💻 أجهزة حاسوب جبارة حديثة', '🎉 مكافآت للمشاريع الناجحة'],
      description: 'مطلوب مصمم مبدع لإعداد منشورات السوشيال ميديا وتعديل مقاطع الـ Reels وTikTok للعملاء.',
      requirements: ['إتقان Photoshop, Premiere, After Effects', 'حس فني عالي وعين للموضة والترندات'],
      howToApply: 'إرسال البورتفوليو برابط الأعمال عبر الواتساب',
      contactPhone: '0794455667',
      contactWhatsapp: '962794455667',
      isUrgent: false,
      status: 'active',
      createdAt: Date.now() - 86400000 * 4
    },
    {
      isDemo: true,
      title: 'مدرب لياقة بدنية وبناء أجسام',
      company: 'مركز نيو لايف للياقة البدنية',
      category: 'رياضة وصحة',
      jobType: 'دوام كامل',
      location: 'شارع فلسطين - إربد',
      salary: '300 - 380 دينار + عمولة تدريب شخصي',
      workHours: 'شفت مسائي من 3:00 حتى 11:00',
      experienceLevel: 'خبرة في التدريب الرياضي',
      genderPreference: 'males',
      benefits: ['🏋️ اشتراك مجاني بالنادي', '💰 عمولات التدريب الخاص (PT)'],
      description: 'مطلوب مدرب لياقة لإرشاد المشتركين على الأجهزة الرياضية ووضع برامج التغذية والتخسيس.',
      requirements: ['معرفة ممتازة بتشريح العضلات والأنظمة الغذائية', 'اللباقة والقدرة على تحفيز الأفراد'],
      howToApply: 'زيارة النادي شخصياً للتواصل مع الإدارة',
      contactPhone: '0779900112',
      contactWhatsapp: '962779900112',
      isUrgent: false,
      status: 'active',
      createdAt: Date.now() - 86400000 * 5
    },
    {
      isDemo: true,
      title: 'موظف خدمة عملاء هاتفية ومحادثات (عن بعد)',
      company: 'شركة أوراسكوم للخدمات التسويقية',
      category: 'عن بعد / خدمة عملاء',
      jobType: 'عن بعد',
      location: 'عمل من المنزل (إربد)',
      salary: '300 دينار ثابت',
      workHours: '6 ساعات يومياً متغيرة',
      experienceLevel: 'بدون خبرة (يشترط توفر إنترنت)',
      genderPreference: 'all',
      benefits: ['🏠 عمل مريح بالكامل من المنزل', '🎓 مناسب جداً للطلبة والأمهات'],
      description: 'الرد على استفسارات العملاء وشكاويهم عبر محادثات الواتساب والهاتف وتوجيههم لأقسام الشركة.',
      requirements: ['سرعة الكتابة على الكمبيوتر والهاتف', 'أسلوب لبق ولغة عربية سليمة', 'إنترنت سريع بالمنزل'],
      howToApply: 'التقديم المباشر عبر إرسال رسالة واتساب للرقم المرفق',
      contactPhone: '0780011223',
      contactWhatsapp: '962780011223',
      isUrgent: true,
      status: 'active',
      createdAt: Date.now() - 86400000 * 5
    },
    {
      isDemo: true,
      title: 'خباز ومعلم معجنات وشراك',
      company: 'مخابز وأفران النور الأوتوماتيكية',
      category: 'حلويات ومخابز',
      jobType: 'دوام كامل',
      location: 'حي نزال - إربد',
      salary: '380 - 450 دينار',
      workHours: 'شفت فجري من 4:00 صباحاً حتى 12:00 ظهراً',
      experienceLevel: 'خبرة سنتين في المخابز',
      genderPreference: 'males',
      benefits: ['🍞 خبز ومعجنات مجانية يومياً', '💰 راتب منتظم بدون تأخير'],
      description: 'مطلوب خباز متمرس للعمل على البيت الفرني وتجهيز المعجنات والخبز العربي والفرنسي الطازج.',
      requirements: ['السرعة والخبرة في عجن وقطع وتجهيز المخبوزات', 'الانضباط التام بإنتاج الشفت الصباحي'],
      howToApply: 'الاتصال المباشر مع صاحب المخبز',
      contactPhone: '0795566778',
      contactWhatsapp: '962795566778',
      isUrgent: true,
      status: 'active',
      createdAt: Date.now() - 86400000 * 6
    },
    {
      isDemo: true,
      title: 'موظف طباعة وتصوير مستندات (مناسب للطلاب)',
      company: 'مكتبة وسنتر اليرموك',
      category: 'خدمات طلابية',
      jobType: 'مناسب للطلاب',
      location: 'شارع الجامعة - مقابل اليرموك',
      salary: '280 دينار',
      workHours: 'دوام جزئي يناسب الجدول الجامعي',
      experienceLevel: 'معرفة أساسية بالكمبيوتر والطباعة',
      genderPreference: 'all',
      benefits: ['🎓 ساعات عمل مرنة جداً', '📚 طباعة وتصوير أوراق جامعية مجاناً'],
      description: 'مطلوب طالب جامعي لمساعدة زملائه في طباعة الملخصات والأبحاث وتغليف الكتب في المكتبة.',
      requirements: ['سرعة واستخدام المطبوعات والكمبيوتر', 'حسن الخلق واللباقة'],
      howToApply: 'التقديم المباشر بالمكتبة بالقرب من اليرموك',
      contactPhone: '0798899001',
      contactWhatsapp: '962798899001',
      isUrgent: false,
      status: 'active',
      createdAt: Date.now() - 86400000 * 6
    },
    {
      isDemo: true,
      title: 'فني كهرباء وسيارت هايبرد وكهرباء',
      company: 'مركز الكابتن لصيانة السيارات',
      category: 'صيانة وسيارات',
      jobType: 'دوام كامل',
      location: 'المنطقة الصناعية - إربد',
      salary: '400 - 550 دينار (حسب الكفاءة)',
      workHours: '8:00 صباحاً حتى 5:00 مساءً',
      experienceLevel: 'خبرة 3 سنوات على الأقل في الهايبرد',
      genderPreference: 'males',
      benefits: ['💰 نسبة إضافية على كل فحص كمبيوتر', '✨ بيئة عمل وتجهيزات حديثة'],
      description: 'مطلوب فني كهرباء سيارات متخصص في فحص وبرمجة بطاريات الهايبرد وتحديد الأعطال بدقة عالية.',
      requirements: ['إتقان استخدام أجهزة الفحص الحديثة (Launch / G-Scan)', 'خبرة عملية مؤكدة بالسيارات الهجينة'],
      howToApply: 'الاتصال المباشر لإجراء الاختبار الميداني',
      contactPhone: '0791122334',
      contactWhatsapp: '962791122334',
      isUrgent: true,
      status: 'active',
      createdAt: Date.now() - 86400000 * 7
    },
    {
      isDemo: true,
      title: 'عمال نظافة وضيافة مقهى (شفت صباحي)',
      company: 'كافيه وتراس جدارا',
      category: 'مطاعم ومقاهي',
      jobType: 'دوام كامل',
      location: 'طريق الحصن - إربد',
      salary: '290 - 310 دينار',
      workHours: '8:00 صباحاً حتى 4:00 عصراً',
      experienceLevel: 'مرحب بجميع المتقدمين النشيطين',
      genderPreference: 'males',
      benefits: ['☕ مشروبات ووجبة طعام مجانية', '🎉 إكراميات الزوار'],
      description: 'تنظيف وتنسيق طاولات التراس وتجهيز المقهى لاستقبال الزوار الصباحيين والاهتمام بالنظافة العامة.',
      requirements: ['النشاط والنظافة الشخصية والالتزام بالمواعيد'],
      howToApply: 'الاتصال مباشرة مع إدارة الكافيه',
      contactPhone: '0784455667',
      contactWhatsapp: '962784455667',
      isUrgent: false,
      status: 'active',
      createdAt: Date.now() - 86400000 * 7
    },
    {
      isDemo: true,
      title: 'محاسب مالي ومسؤول صندوق',
      company: 'معرض أثاث ومفروشات الشرق',
      category: 'محاسبة وإدارة',
      jobType: 'دوام كامل',
      location: 'طريق الحصن الرئيسي - إربد',
      salary: '380 - 450 دينار',
      workHours: '9:00 صباحاً حتى 5:00 مساءً',
      experienceLevel: 'بكالوريوس محاسبة + خبرة سنتين',
      genderPreference: 'all',
      benefits: ['✨ ضمان اجتماعي', '🎉 مكافآت سنوية'],
      description: 'إدخال الفواتير اليومية، متابعة الذمم والدفعات، وإعداد القيود المالية والقوائم الختامية للمعرض.',
      requirements: ['بكالوريوس محاسبة بتقدير جيد جداً على الأقل', 'إتقان البرامج المحاسبية (QuickBooks / الشامل)'],
      howToApply: 'إرسال السيرة الذاتية عبر البريد الإلكتروني أو الواتساب',
      contactPhone: '0783344556',
      contactWhatsapp: '962783344556',
      isUrgent: false,
      status: 'active',
      createdAt: Date.now() - 86400000 * 8
    }
  ],

  // News Articles
  news: [
    {
      isDemo: true,
      title: 'بلدية إربد الكبرى تطلق خطة لتطوير وتعبيد وتجميل الشوارع الحيوية',
      excerpt: 'بدأت كوادر بلدية إربد الكبرى بتنفيذ حزمة مشاريع جديدة لتطوير البنية التحتية، وإعادة تأهيل الطرق الرئيسية والإنارة في مختلف مناطق عروس الشمال.',
      category: 'أخبار المدينة',
      date: 'منذ ساعتين',
      readTime: '3 دقائق',
      location: 'وسط البلد، إربد',
      imageUrl: 'https://images.unsplash.com/photo-1577495508048-b635879837f1?auto=format&fit=crop&w=900&q=80',
      isHot: true,
      source: 'إعلام بلدية إربد',
      createdAt: Date.now() - 7200000
    },
    {
      isDemo: true,
      title: 'جامعة اليرموك تعلن عن فعاليات أسبوع الريادة والابتكار والبحث العلمي',
      excerpt: 'تستعد جامعة اليرموك لاستقبال نخبة من المبتكرين والشركات الناشئة في ملتقى الإبداع السنوي، بمشاركة واسعة من طلبة الجامعات والمجتمع المحلي.',
      category: 'تعليم وجامعات',
      date: 'منذ 5 ساعات',
      readTime: '4 دقائق',
      location: 'جامعة اليرموك',
      imageUrl: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=900&q=80',
      isHot: true,
      source: 'دائرة العلاقات العامة - اليرموك',
      createdAt: Date.now() - 18000000
    }
  ],

  // Offers
  offers: [
    {
      isDemo: true,
      title: 'عرض الوجبة العائلية: 2 بيتزا كبيرة + بطاطا ولتر كولا',
      businessName: 'بيتزا روما الإيطالية',
      category: 'مطاعم ومقاهي',
      discountPercentage: '35%',
      oldPrice: '18 د.أ',
      newPrice: '11.70 د.أ',
      code: 'ROMA35',
      expiresIn: 'ينتهي خلال 3 أيام',
      description: 'استمتع بأشهى بيتزا حطب إيطالية في إربد مع جبنة الموزاريلا الفاخرة.',
      location: 'شارع الجامعة - قرب إشارة الإسكان',
      phone: '0785544332',
      whatsapp: '962785544332',
      image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&q=80&w=800',
      isHot: true,
      createdAt: Date.now() - 3600000 * 6
    },
    {
      isDemo: true,
      title: 'خصم خاص لطلبة الجامعات على جميع مشروبات القهوة المختصة',
      businessName: 'كافيه لافا (Lava Coffee)',
      category: 'مطاعم ومقاهي',
      discountPercentage: '25%',
      oldPrice: '2.50 د.أ',
      newPrice: '1.85 د.أ',
      code: 'STUDENT25',
      expiresIn: 'ساري طوال الفصل الدراسي',
      description: 'أظهر هويتك الجامعية (اليرموك، التكنو، جدارا) واحصل على خصم فوري.',
      location: 'شارع الجامعة - مقابل البوابة الشمالية لليرموك',
      phone: '0788123456',
      whatsapp: '962788123456',
      image: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&q=80&w=800',
      isStudent: true,
      isHot: true,
      createdAt: Date.now() - 3600000 * 10
    }
  ],

  // Notifications
  notifications: [
    {
      isDemo: true,
      title: 'خصم خاص 30% في مطعم ومقهى ديوان زمان',
      message: 'استمتع بأشهى الوجبات والمشروبات بخصم مميز لفترة محدودة على شارع الجامعة.',
      type: 'offer',
      link: '/offers',
      createdAt: Date.now() - 1000 * 60 * 15,
      badge: 'عرض جديد 🔥',
      userId: 'all'
    },
    {
      isDemo: true,
      title: 'أهلاً بك في منصة شو في بإربد! 🌟',
      message: 'دليلك الشامل الذكي لاكتشاف أفضل المحلات، المطاعم، والخدمات في عروس الشمال.',
      type: 'system',
      link: '/',
      createdAt: Date.now() - 1000 * 60 * 60 * 48,
      badge: 'ترحيب 👋',
      userId: 'all'
    }
  ]
};

export async function seedDemoDataToFirestore(): Promise<{ count: number }> {
  if (!db) throw new Error('Database connection not available');

  let totalAdded = 0;

  // Seed Businesses (20)
  for (const b of DEMO_SEED_DATA.businesses) {
    await addDoc(collection(db, 'businesses'), b);
    totalAdded++;
  }

  // Seed Housings (20)
  for (const h of DEMO_SEED_DATA.housings) {
    await addDoc(collection(db, 'housings'), h);
    totalAdded++;
  }

  // Seed Jobs (20)
  for (const j of DEMO_SEED_DATA.jobs) {
    await addDoc(collection(db, 'jobs'), j);
    totalAdded++;
  }

  // Seed News
  for (const n of DEMO_SEED_DATA.news) {
    await addDoc(collection(db, 'news'), n);
    totalAdded++;
  }

  // Seed Offers
  for (const o of DEMO_SEED_DATA.offers) {
    await addDoc(collection(db, 'offers'), o);
    totalAdded++;
  }

  // Seed Notifications
  for (const notif of DEMO_SEED_DATA.notifications) {
    await addDoc(collection(db, 'notifications'), notif);
    totalAdded++;
  }

  // Enable showDemoData in appConfig
  await setAppConfig({ showDemoData: true });

  return { count: totalAdded };
}

export async function clearDemoDataFromFirestore(): Promise<{ count: number }> {
  if (!db) throw new Error('Database connection not available');

  let totalDeleted = 0;
  const collectionsToClean = ['businesses', 'jobs', 'news', 'offers', 'notifications', 'housings'];

  for (const colName of collectionsToClean) {
    try {
      const q = query(collection(db, colName), where('isDemo', '==', true));
      const snap = await getDocs(q);
      for (const d of snap.docs) {
        await deleteDoc(doc(db, colName, d.id));
        totalDeleted++;
      }
    } catch (err) {
      console.warn(`Error cleaning demo data from ${colName}:`, err);
    }
  }

  return { count: totalDeleted };
}
