import { PosterTemplate } from '../../../types/posterDesigner';

export const CANVAS_FORMATS = {
  a4_portrait: { name: 'A4 قياسي عمودي', width: 794, height: 1123 },
  a4_landscape: { name: 'A4 أفقي', width: 1123, height: 794 },
  a5_portrait: { name: 'A5 نصف ورقة', width: 560, height: 794 },
  table_tent: { name: 'ستاند طاولة Tent', width: 600, height: 900 },
  square_sticker: { name: 'ستيكر مربع', width: 700, height: 700 }
};

export const PRESET_TEMPLATES: PosterTemplate[] = [
  {
    id: 'modern_flyer',
    title: 'فلاير عصري إنسيابي (Modern Flyer)',
    description: 'التصميم الاحترافي المتداخل مع تموج إنسيابي، صورة وجبة دائرية، وقسم مسح متقدم.',
    format: 'a4_portrait',
    canvasWidth: 794,
    canvasHeight: 1123,
    backgroundColor: '#ffffff',
    isSystemPreset: true,
    isDefault: true,
    elements: [
      // 1. Top Header Background
      {
        id: 'el-top-header-bg',
        type: 'shape_rect',
        name: 'شريط الهيدر العلوي',
        x: 0,
        y: 0,
        width: 794,
        height: 140,
        zIndex: 1,
        backgroundColor: '#ffffff',
        borderWidth: 0
      },
      // 2. Business Logo
      {
        id: 'el-logo',
        type: 'logo',
        name: 'شعار المحل',
        x: 644,
        y: 25,
        width: 90,
        height: 90,
        zIndex: 10,
        borderRadius: 20,
        borderWidth: 2,
        borderColor: '#e5e7eb',
        clipShape: 'rounded'
      },
      // 3. Business Name
      {
        id: 'el-biz-name',
        type: 'business_name',
        name: 'اسم المحل التجاري',
        x: 230,
        y: 32,
        width: 395,
        height: 48,
        zIndex: 10,
        text: '{{business_name}}',
        fontSize: 32,
        fontWeight: '900',
        fontFamily: 'Cairo, sans-serif',
        color: '#111827',
        textAlign: 'right'
      },
      // 4. Subtitle / Category
      {
        id: 'el-category-badge',
        type: 'subtitle',
        name: 'تصنيف المنشأة',
        x: 350,
        y: 84,
        width: 275,
        height: 32,
        zIndex: 10,
        text: '{{category}} • تجربة طعام استثنائية',
        fontSize: 14,
        fontWeight: '700',
        fontFamily: 'Cairo, sans-serif',
        color: '#4b5563',
        textAlign: 'right'
      },
      // 5. Digital Menu Badge
      {
        id: 'el-digital-badge',
        type: 'shape_badge',
        name: 'شارة منيو رقمي',
        x: 40,
        y: 45,
        width: 150,
        height: 40,
        zIndex: 10,
        text: '✨ منيو إلكتروني ذكي',
        fontSize: 13,
        fontWeight: '800',
        fontFamily: 'Cairo, sans-serif',
        color: '#065f46',
        backgroundColor: '#ecfdf5',
        borderRadius: 99,
        borderColor: '#a7f3d0',
        borderWidth: 1.5,
        textAlign: 'center'
      },
      // 6. Middle Scan Card
      {
        id: 'el-scan-card',
        type: 'shape_rect',
        name: 'بطاقة المسح العلوية',
        x: 40,
        y: 160,
        width: 714,
        height: 340,
        zIndex: 5,
        backgroundColor: '#f8fafc',
        borderRadius: 32,
        borderWidth: 2,
        borderColor: '#e2e8f0',
        boxShadow: '0 10px 25px -5px rgba(0, 0, 0, 0.05)'
      },
      // 7. QR Code Frame Box
      {
        id: 'el-qr-box',
        type: 'qr_code',
        name: 'رمز الـ QR الرئيسي',
        x: 460,
        y: 190,
        width: 260,
        height: 260,
        zIndex: 15,
        qrColor: '#0f766e',
        qrBgColor: '#ffffff',
        qrCenterLogo: true,
        borderRadius: 24,
        borderColor: '#0f766e',
        borderWidth: 4,
        padding: 16,
        boxShadow: '0 20px 25px -5px rgba(15, 118, 110, 0.15)'
      },
      // 8. Scan Headline (Arabic)
      {
        id: 'el-scan-title',
        type: 'hero_title',
        name: 'عنوان المسح الرئيسي',
        x: 80,
        y: 200,
        width: 350,
        height: 50,
        zIndex: 12,
        text: 'امسـح الكـود 📱',
        fontSize: 34,
        fontWeight: '900',
        fontFamily: 'Cairo, sans-serif',
        color: '#0f766e',
        textAlign: 'right'
      },
      // 9. Scan Subtitle (Arabic)
      {
        id: 'el-scan-sub',
        type: 'subtitle',
        name: 'نص التوجيه للمسح',
        x: 80,
        y: 260,
        width: 350,
        height: 48,
        zIndex: 12,
        text: 'تصفح قائمة الطعام، العروض الخاصة والأسعار المحدثة لحظياً عبر هاتفك',
        fontSize: 15,
        fontWeight: '600',
        fontFamily: 'Cairo, sans-serif',
        color: '#334155',
        textAlign: 'right',
        lineHeight: 1.5
      },
      // 10. Table Number / English Badge
      {
        id: 'el-table-badge',
        type: 'table_number',
        name: 'رقم الطاولة / الترحيب',
        x: 80,
        y: 330,
        width: 340,
        height: 44,
        zIndex: 12,
        text: '🍽️ نتشرف بخدمتكم • أهلاً وسهلاً بكم',
        fontSize: 14,
        fontWeight: '800',
        fontFamily: 'Cairo, sans-serif',
        color: '#047857',
        backgroundColor: '#d1fae5',
        borderRadius: 14,
        borderColor: '#6ee7b7',
        borderWidth: 1.5,
        textAlign: 'center'
      },
      // 11. Instructions hint
      {
        id: 'el-instructions',
        type: 'custom_text',
        name: 'تعليمات الكاميرا',
        x: 80,
        y: 395,
        width: 350,
        height: 30,
        zIndex: 12,
        text: '📷 افتح كاميرا هاتفك ووجّهها نحو الرمز مباشرة',
        fontSize: 13,
        fontWeight: '700',
        fontFamily: 'Cairo, sans-serif',
        color: '#64748b',
        textAlign: 'right'
      },
      // 12. Wave Background Accent
      {
        id: 'el-wave-section',
        type: 'shape_rect',
        name: 'خلفية القسم السفلي التموجي',
        x: 0,
        y: 540,
        width: 794,
        height: 460,
        zIndex: 2,
        backgroundColor: '#0f766e',
        backgroundGradient: {
          from: '#0f766e',
          to: '#115e59',
          direction: 'to bottom'
        },
        borderRadius: 40
      },
      // 13. Circular Food Image
      {
        id: 'el-food-photo',
        type: 'food_photo',
        name: 'صورة الوجبة الترويجية الدائرية',
        x: 40,
        y: 500,
        width: 250,
        height: 250,
        zIndex: 20,
        src: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=600&q=80',
        borderRadius: 999,
        borderWidth: 8,
        borderColor: '#ffffff',
        clipShape: 'circle',
        boxShadow: '0 25px 50px -12px rgba(0, 0, 0, 0.25)'
      },
      // 14. Bottom Wave Text - Title
      {
        id: 'el-wave-title',
        type: 'hero_title',
        name: 'عنوان القسم التموجي',
        x: 320,
        y: 600,
        width: 430,
        height: 50,
        zIndex: 10,
        text: 'استمتع بأشهى المأكولات والمشروبات',
        fontSize: 26,
        fontWeight: '900',
        fontFamily: 'Cairo, sans-serif',
        color: '#ffffff',
        textAlign: 'right'
      },
      // 15. Bottom Wave Text - Subtitle
      {
        id: 'el-wave-sub',
        type: 'subtitle',
        name: 'وصف القسم التموجي',
        x: 320,
        y: 660,
        width: 430,
        height: 60,
        zIndex: 10,
        text: 'نختار أجود المكونات الطازجة لنقدم لكم تجربة استثنائية لا تُنسى في كل زيارة.',
        fontSize: 16,
        fontWeight: '600',
        fontFamily: 'Cairo, sans-serif',
        color: '#ccfbf1',
        textAlign: 'right',
        lineHeight: 1.6
      },
      // 16. English Slogan Badge
      {
        id: 'el-english-slogan',
        type: 'english_text',
        name: 'الشعار الإنجليزي',
        x: 320,
        y: 745,
        width: 410,
        height: 42,
        zIndex: 10,
        text: 'SCAN TO EXPLORE OUR DELICIOUS MENU',
        fontSize: 13,
        fontWeight: '800',
        fontFamily: 'Inter, sans-serif',
        color: '#fef08a',
        backgroundColor: 'rgba(255, 255, 255, 0.12)',
        borderRadius: 99,
        borderColor: 'rgba(255, 255, 255, 0.25)',
        borderWidth: 1.5,
        textAlign: 'center',
        letterSpacing: 1
      },
      // 17. Working Hours Pill
      {
        id: 'el-hours-badge',
        type: 'working_hours',
        name: 'أوقات العمل',
        x: 320,
        y: 810,
        width: 410,
        height: 44,
        zIndex: 10,
        text: '⏰ أوقات العمل: {{working_hours}}',
        fontSize: 14,
        fontWeight: '700',
        fontFamily: 'Cairo, sans-serif',
        color: '#ffffff',
        backgroundColor: 'rgba(0, 0, 0, 0.2)',
        borderRadius: 14,
        textAlign: 'center'
      },
      // 18. Clean Footer Bar
      {
        id: 'el-footer-bg',
        type: 'shape_rect',
        name: 'خلفية الفوتر الأبيض',
        x: 0,
        y: 1020,
        width: 794,
        height: 103,
        zIndex: 1,
        backgroundColor: '#ffffff',
        borderWidth: 0
      },
      // 19. Footer Platform Branding
      {
        id: 'el-footer-branding',
        type: 'platform_branding',
        name: 'شعار ورابط الموقع',
        x: 40,
        y: 1030,
        width: 340,
        height: 75,
        zIndex: 10,
        text: 'shofibirbid.site',
        fontSize: 13,
        fontWeight: '800',
        fontFamily: 'Cairo, sans-serif',
        color: '#1a4d2e',
        textAlign: 'left'
      },
      // 20. Footer Contact / Phone
      {
        id: 'el-footer-phone',
        type: 'contact_bar',
        name: 'هاتف المحل',
        x: 420,
        y: 1040,
        width: 334,
        height: 40,
        zIndex: 10,
        text: '📞 للطلب والاستفسار: {{phone}}',
        fontSize: 14,
        fontWeight: '800',
        fontFamily: 'Cairo, sans-serif',
        color: '#334155',
        textAlign: 'right'
      }
    ]
  },
  {
    id: 'luxury_gold',
    title: 'الأسود والذهبي الفاخر (Luxury Black & Gold)',
    description: 'قالب كلاسيكي ملكي للمطاعم الراقية، الفنادق، ومقاهي النخبة بخلفية سوداء ولمسات ذهبية.',
    format: 'a4_portrait',
    canvasWidth: 794,
    canvasHeight: 1123,
    backgroundColor: '#0f172a',
    isSystemPreset: true,
    elements: [
      {
        id: 'el-gold-border',
        type: 'shape_rect',
        name: 'الإطار الذهبي الخارجي',
        x: 25,
        y: 25,
        width: 744,
        height: 1073,
        zIndex: 1,
        backgroundColor: 'transparent',
        borderColor: '#d97706',
        borderWidth: 3,
        borderRadius: 24
      },
      {
        id: 'el-gold-inner-border',
        type: 'shape_rect',
        name: 'الإطار الذهبي الداخلي',
        x: 35,
        y: 35,
        width: 724,
        height: 1053,
        zIndex: 2,
        backgroundColor: 'transparent',
        borderColor: '#fbbf24',
        borderWidth: 1,
        borderRadius: 18,
        borderStyle: 'dashed'
      },
      {
        id: 'el-gold-logo',
        type: 'logo',
        name: 'شعار المنشأة',
        x: 337,
        y: 70,
        width: 120,
        height: 120,
        zIndex: 10,
        borderRadius: 999,
        borderWidth: 3,
        borderColor: '#fbbf24',
        clipShape: 'circle'
      },
      {
        id: 'el-gold-biz-name',
        type: 'business_name',
        name: 'اسم المنشأة الفاخر',
        x: 70,
        y: 210,
        width: 654,
        height: 50,
        zIndex: 10,
        text: '{{business_name}}',
        fontSize: 36,
        fontWeight: '900',
        fontFamily: 'Amiri, serif',
        color: '#fef08a',
        textAlign: 'center',
        letterSpacing: 1
      },
      {
        id: 'el-gold-subtitle',
        type: 'subtitle',
        name: 'العبارة الملكية',
        x: 70,
        y: 270,
        width: 654,
        height: 35,
        zIndex: 10,
        text: '• أرقى المأكولات والمشروبات في إربد •',
        fontSize: 16,
        fontWeight: '700',
        fontFamily: 'Cairo, sans-serif',
        color: '#e2e8f0',
        textAlign: 'center'
      },
      {
        id: 'el-gold-qr',
        type: 'qr_code',
        name: 'رمز الاستجابة الذهبي',
        x: 237,
        y: 340,
        width: 320,
        height: 320,
        zIndex: 15,
        qrColor: '#0f172a',
        qrBgColor: '#ffffff',
        qrCenterLogo: true,
        borderRadius: 28,
        borderColor: '#fbbf24',
        borderWidth: 6,
        padding: 20,
        boxShadow: '0 25px 50px -12px rgba(251, 191, 36, 0.25)'
      },
      {
        id: 'el-gold-scan-callout',
        type: 'hero_title',
        name: 'عنوان المسح',
        x: 70,
        y: 690,
        width: 654,
        height: 45,
        zIndex: 10,
        text: 'تفضل بمسح الرمز لاستعراض المنيو الفاخر',
        fontSize: 24,
        fontWeight: '900',
        fontFamily: 'Cairo, sans-serif',
        color: '#fbbf24',
        textAlign: 'center'
      },
      {
        id: 'el-gold-en-text',
        type: 'english_text',
        name: 'English Menu Headline',
        x: 120,
        y: 750,
        width: 554,
        height: 40,
        zIndex: 10,
        text: 'EXCLUSIVE VIP DIGITAL MENU & WINE / COFFEE LIST',
        fontSize: 14,
        fontWeight: '800',
        fontFamily: 'Inter, sans-serif',
        color: '#94a3b8',
        textAlign: 'center',
        letterSpacing: 2
      },
      {
        id: 'el-gold-phone',
        type: 'contact_bar',
        name: 'معلومات الحجز والاتصال',
        x: 100,
        y: 830,
        width: 594,
        height: 60,
        zIndex: 10,
        text: 'للحجوزات الخاصة والاستفسارات: {{phone}}',
        fontSize: 18,
        fontWeight: '800',
        fontFamily: 'Cairo, sans-serif',
        color: '#ffffff',
        backgroundColor: 'rgba(251, 191, 36, 0.1)',
        borderColor: '#d97706',
        borderWidth: 1.5,
        borderRadius: 16,
        textAlign: 'center'
      },
      {
        id: 'el-gold-footer',
        type: 'platform_branding',
        name: 'شعار ورابط الموقع',
        x: 70,
        y: 1015,
        width: 654,
        height: 75,
        zIndex: 10,
        text: 'shofibirbid.site',
        fontSize: 13,
        fontWeight: '700',
        fontFamily: 'Cairo, sans-serif',
        color: '#d4af37',
        textAlign: 'center'
      }
    ]
  },
  {
    id: 'warm_cafe',
    title: 'الكافيه والمخبز الدافئ (Warm Coffee & Bakery)',
    description: 'ألوان القهوة والكراميل الدافئة والتصميم المريح المناسب للمقاهي والمحامص والمخابز.',
    format: 'a4_portrait',
    canvasWidth: 794,
    canvasHeight: 1123,
    backgroundColor: '#fffbeb',
    isSystemPreset: true,
    elements: [
      {
        id: 'el-cafe-banner',
        type: 'shape_rect',
        name: 'بانر القهوة العلوي',
        x: 40,
        y: 40,
        width: 714,
        height: 200,
        zIndex: 1,
        backgroundColor: '#78350f',
        borderRadius: 28
      },
      {
        id: 'el-cafe-logo',
        type: 'logo',
        name: 'شعار الكافيه',
        x: 80,
        y: 75,
        width: 130,
        height: 130,
        zIndex: 10,
        borderRadius: 24,
        borderWidth: 3,
        borderColor: '#fef3c7',
        clipShape: 'rounded'
      },
      {
        id: 'el-cafe-name',
        type: 'business_name',
        name: 'اسم الكافيه',
        x: 230,
        y: 80,
        width: 490,
        height: 50,
        zIndex: 10,
        text: '{{business_name}}',
        fontSize: 34,
        fontWeight: '900',
        fontFamily: 'Cairo, sans-serif',
        color: '#fef3c7',
        textAlign: 'right'
      },
      {
        id: 'el-cafe-slogan',
        type: 'subtitle',
        name: 'شعار القهوة',
        x: 230,
        y: 140,
        width: 490,
        height: 40,
        zIndex: 10,
        text: '☕ قهوة مختصة، حلويات طازجة ومشروبات منعشة',
        fontSize: 16,
        fontWeight: '700',
        fontFamily: 'Cairo, sans-serif',
        color: '#fde68a',
        textAlign: 'right'
      },
      {
        id: 'el-cafe-qr',
        type: 'qr_code',
        name: 'رمز الـ QR للكافيه',
        x: 247,
        y: 300,
        width: 300,
        height: 300,
        zIndex: 15,
        qrColor: '#78350f',
        qrBgColor: '#ffffff',
        qrCenterLogo: true,
        borderRadius: 24,
        borderColor: '#b45309',
        borderWidth: 4,
        padding: 18,
        boxShadow: '0 20px 30px -10px rgba(120, 53, 15, 0.2)'
      },
      {
        id: 'el-cafe-scan-title',
        type: 'hero_title',
        name: 'عنوان منيو المشروبات والحلويات',
        x: 70,
        y: 640,
        width: 654,
        height: 45,
        zIndex: 10,
        text: 'امسح وتذوق نكهاتنا المميزة 🍰☕',
        fontSize: 28,
        fontWeight: '900',
        fontFamily: 'Cairo, sans-serif',
        color: '#78350f',
        textAlign: 'center'
      },
      {
        id: 'el-cafe-subtext',
        type: 'custom_text',
        name: 'نص التوجيه الدافئ',
        x: 70,
        y: 700,
        width: 654,
        height: 40,
        zIndex: 10,
        text: 'تصفح قائمة القهوة المختصة، السموثي، الوافل والحلويات لحظة بلحظة',
        fontSize: 16,
        fontWeight: '600',
        fontFamily: 'Cairo, sans-serif',
        color: '#92400e',
        textAlign: 'center'
      },
      {
        id: 'el-cafe-table',
        type: 'table_number',
        name: 'شارة الطاولة',
        x: 220,
        y: 770,
        width: 354,
        height: 50,
        zIndex: 10,
        text: 'طاولة رقم ☕ 01',
        fontSize: 18,
        fontWeight: '900',
        fontFamily: 'Cairo, sans-serif',
        color: '#78350f',
        backgroundColor: '#fef3c7',
        borderRadius: 99,
        borderColor: '#d97706',
        borderWidth: 2,
        textAlign: 'center'
      },
      {
        id: 'el-cafe-hours',
        type: 'working_hours',
        name: 'ساعات العمل',
        x: 70,
        y: 860,
        width: 654,
        height: 45,
        zIndex: 10,
        text: '⏰ نستقبلكم يومياً: {{working_hours}}',
        fontSize: 16,
        fontWeight: '800',
        fontFamily: 'Cairo, sans-serif',
        color: '#78350f',
        textAlign: 'center'
      },
      {
        id: 'el-cafe-footer',
        type: 'platform_branding',
        name: 'شعار ورابط الموقع',
        x: 70,
        y: 1025,
        width: 654,
        height: 75,
        zIndex: 10,
        text: 'shofibirbid.site',
        fontSize: 13,
        fontWeight: '700',
        fontFamily: 'Cairo, sans-serif',
        color: '#b45309',
        textAlign: 'center'
      }
    ]
  },
  {
    id: 'fast_food_red',
    title: 'الوجبات السريعة والبرجر (Fast Food Flame Red)',
    description: 'تصميم ديناميكي حيوي بألوان الأحمر والأصفر لإثارة الشهية وجذب الزبائن بسرعة.',
    format: 'a4_portrait',
    canvasWidth: 794,
    canvasHeight: 1123,
    backgroundColor: '#dc2626',
    isSystemPreset: true,
    elements: [
      {
        id: 'el-ff-top-banner',
        type: 'shape_rect',
        name: 'الهيدر الأبيض',
        x: 0,
        y: 0,
        width: 794,
        height: 160,
        zIndex: 1,
        backgroundColor: '#ffffff'
      },
      {
        id: 'el-ff-logo',
        type: 'logo',
        name: 'شعار المطعم',
        x: 620,
        y: 30,
        width: 100,
        height: 100,
        zIndex: 10,
        borderRadius: 20,
        borderWidth: 3,
        borderColor: '#dc2626',
        clipShape: 'rounded'
      },
      {
        id: 'el-ff-biz-name',
        type: 'business_name',
        name: 'اسم مطعم الوجبات',
        x: 200,
        y: 45,
        width: 400,
        height: 45,
        zIndex: 10,
        text: '{{business_name}}',
        fontSize: 32,
        fontWeight: '900',
        fontFamily: 'Cairo, sans-serif',
        color: '#dc2626',
        textAlign: 'right'
      },
      {
        id: 'el-ff-sub',
        type: 'subtitle',
        name: 'الشعار الحماسي',
        x: 200,
        y: 95,
        width: 400,
        height: 35,
        zIndex: 10,
        text: '🔥 برجر طازج • مقرمشات • وجبات كومبو',
        fontSize: 15,
        fontWeight: '800',
        fontFamily: 'Cairo, sans-serif',
        color: '#475569',
        textAlign: 'right'
      },
      {
        id: 'el-ff-hero-title',
        type: 'hero_title',
        name: 'امسح واطلب وجبتك',
        x: 40,
        y: 200,
        width: 714,
        height: 60,
        zIndex: 10,
        text: 'امسح الكود وشوف أقوى العروض والوجبات!',
        fontSize: 30,
        fontWeight: '900',
        fontFamily: 'Cairo, sans-serif',
        color: '#fef08a',
        textAlign: 'center'
      },
      {
        id: 'el-ff-qr',
        type: 'qr_code',
        name: 'الباركود',
        x: 237,
        y: 280,
        width: 320,
        height: 320,
        zIndex: 15,
        qrColor: '#b91c1c',
        qrBgColor: '#ffffff',
        qrCenterLogo: true,
        borderRadius: 28,
        borderColor: '#facc15',
        borderWidth: 6,
        padding: 18,
        boxShadow: '0 25px 50px -12px rgba(0, 0, 0, 0.4)'
      },
      {
        id: 'el-ff-delivery-pill',
        type: 'shape_badge',
        name: 'خدمة التوصيل السريع',
        x: 180,
        y: 630,
        width: 434,
        height: 50,
        zIndex: 10,
        text: '🚀 توصيل سريع لكافة مناطق إربد',
        fontSize: 18,
        fontWeight: '900',
        fontFamily: 'Cairo, sans-serif',
        color: '#991b1b',
        backgroundColor: '#fef08a',
        borderRadius: 99,
        textAlign: 'center'
      },
      {
        id: 'el-ff-food-img',
        type: 'food_photo',
        name: 'صورة البرجر الترويجية',
        x: 237,
        y: 710,
        width: 320,
        height: 200,
        zIndex: 10,
        src: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=600&q=80',
        borderRadius: 24,
        borderWidth: 4,
        borderColor: '#ffffff',
        boxShadow: '0 20px 25px -5px rgba(0, 0, 0, 0.3)'
      },
      {
        id: 'el-ff-footer-call',
        type: 'contact_bar',
        name: 'هاتف الطلبات',
        x: 40,
        y: 950,
        width: 714,
        height: 50,
        zIndex: 10,
        text: '📞 للطلب والتوصيل المباشر: {{phone}}',
        fontSize: 20,
        fontWeight: '900',
        fontFamily: 'Cairo, sans-serif',
        color: '#ffffff',
        textAlign: 'center'
      },
      {
        id: 'el-ff-footer-platform',
        type: 'platform_branding',
        name: 'شعار ورابط الموقع',
        x: 40,
        y: 1025,
        width: 714,
        height: 75,
        zIndex: 10,
        text: 'shofibirbid.site',
        fontSize: 14,
        fontWeight: '800',
        fontFamily: 'Cairo, sans-serif',
        color: '#ffffff',
        textAlign: 'center'
      }
    ]
  }
];

export const PRESET_REVIEWS_TEMPLATES: PosterTemplate[] = [
  // 1. Classic Emerald & Blue
  {
    id: 'reviews_classic_flyer',
    title: 'الكلاسيكي الأنيق (Classic Emerald)',
    description: 'قالب كارت تقييم وآراء مميز يشجع الزوار والمرضى على مسح الرمز وتقييم تجربتهم.',
    format: 'a4_portrait',
    canvasWidth: 794,
    canvasHeight: 1123,
    backgroundColor: '#ffffff',
    isSystemPreset: true,
    isDefault: true,
    elements: [
      {
        id: 'el-top-bg',
        type: 'shape_rect',
        name: 'الهيدر العلوي',
        x: 0,
        y: 0,
        width: 794,
        height: 150,
        zIndex: 1,
        backgroundColor: '#ffffff'
      },
      {
        id: 'el-logo',
        type: 'logo',
        name: 'شعار المنشأة',
        x: 644,
        y: 25,
        width: 95,
        height: 95,
        zIndex: 10,
        borderRadius: 20,
        borderWidth: 2,
        borderColor: '#e5e7eb',
        clipShape: 'rounded'
      },
      {
        id: 'el-biz-name',
        type: 'business_name',
        name: 'اسم المنشأة',
        x: 220,
        y: 35,
        width: 400,
        height: 48,
        zIndex: 10,
        text: '{{business_name}}',
        fontSize: 32,
        fontWeight: '900',
        fontFamily: 'Cairo, sans-serif',
        color: '#111827',
        textAlign: 'right'
      },
      {
        id: 'el-rating-stars',
        type: 'rating_badge',
        name: 'شارة التقييم والنجوم',
        x: 220,
        y: 88,
        width: 320,
        height: 36,
        zIndex: 10,
        text: '⭐⭐⭐⭐⭐ تقييمات وآراء الزوار',
        fontSize: 15,
        fontWeight: '800',
        fontFamily: 'Cairo, sans-serif',
        color: '#d97706',
        backgroundColor: '#fef3c7',
        borderRadius: 99,
        borderColor: '#fde68a',
        borderWidth: 1.5,
        textAlign: 'center'
      },
      {
        id: 'el-scan-card',
        type: 'shape_rect',
        name: 'بطاقة المراجعات والمسح',
        x: 50,
        y: 180,
        width: 694,
        height: 380,
        zIndex: 5,
        backgroundColor: '#f8fafc',
        borderRadius: 32,
        borderWidth: 2,
        borderColor: '#e2e8f0',
        boxShadow: '0 10px 25px -5px rgba(0, 0, 0, 0.05)'
      },
      {
        id: 'el-qr-box',
        type: 'qr_code',
        name: 'رمز الـ QR للتقييم',
        x: 440,
        y: 210,
        width: 270,
        height: 270,
        zIndex: 15,
        qrColor: '#0284c7',
        qrBgColor: '#ffffff',
        qrCenterLogo: true,
        borderRadius: 24,
        borderColor: '#0284c7',
        borderWidth: 4,
        padding: 16,
        boxShadow: '0 20px 25px -5px rgba(2, 132, 199, 0.15)'
      },
      {
        id: 'el-scan-title',
        type: 'hero_title',
        name: 'عنوان المراجعات والتقييم',
        x: 80,
        y: 220,
        width: 340,
        height: 52,
        zIndex: 12,
        text: 'قيم تجربتك ورأيك يهمنا ✨',
        fontSize: 30,
        fontWeight: '900',
        fontFamily: 'Cairo, sans-serif',
        color: '#0369a1',
        textAlign: 'right'
      },
      {
        id: 'el-scan-sub',
        type: 'subtitle',
        name: 'وصف التقييم وتوجيه الزائر',
        x: 80,
        y: 282,
        width: 340,
        height: 60,
        zIndex: 12,
        text: 'امسح الكود بكاميرا هاتفك لتقييم تجربتك ورأيك الصادق لمساعدتنا في تقديم أفضل خدمة دائماً',
        fontSize: 14,
        fontWeight: '600',
        fontFamily: 'Cairo, sans-serif',
        color: '#334155',
        textAlign: 'right',
        lineHeight: 1.5
      },
      {
        id: 'el-gift-badge',
        type: 'shape_badge',
        name: 'شارة برنامج المكافآت',
        x: 80,
        y: 360,
        width: 330,
        height: 44,
        zIndex: 12,
        text: '🎁 احصل على كود خصم فوري عند تقييمك!',
        fontSize: 13,
        fontWeight: '800',
        fontFamily: 'Cairo, sans-serif',
        color: '#047857',
        backgroundColor: '#d1fae5',
        borderRadius: 14,
        borderColor: '#6ee7b7',
        borderWidth: 1.5,
        textAlign: 'center'
      },
      {
        id: 'el-wave-bottom',
        type: 'shape_wave',
        name: 'الموجة التزيينية السفلية',
        x: 0,
        y: 600,
        width: 794,
        height: 420,
        zIndex: 2,
        backgroundColor: '#0284c7'
      },
      {
        id: 'el-wave-title',
        type: 'hero_title',
        name: 'عنوان القسم السفلي للتقييم',
        x: 50,
        y: 680,
        width: 694,
        height: 50,
        zIndex: 10,
        text: 'خدمتكم ورضاكم هو هدفنا الأسمى ❤️',
        fontSize: 28,
        fontWeight: '900',
        fontFamily: 'Cairo, sans-serif',
        color: '#ffffff',
        textAlign: 'center'
      },
      {
        id: 'el-wave-sub',
        type: 'subtitle',
        name: 'وصف القسم السفلي للتقييم',
        x: 100,
        y: 740,
        width: 594,
        height: 48,
        zIndex: 10,
        text: 'يسعدنا دائماً الاستماع لملاحظاتكم وتطوير خدماتنا لتليق بكم',
        fontSize: 16,
        fontWeight: '600',
        fontFamily: 'Cairo, sans-serif',
        color: '#e0f2fe',
        textAlign: 'center'
      },
      {
        id: 'el-footer-branding',
        type: 'platform_branding',
        name: 'هوية المنصة وشعار شو في بإربد',
        x: 50,
        y: 1040,
        width: 694,
        height: 50,
        zIndex: 20,
        text: 'تم الإصدار عبر منصة شوف إربد الرقمية • shoofirbid.com',
        fontSize: 13,
        fontWeight: '700',
        color: '#64748b',
        textAlign: 'center'
      }
    ]
  },

  // 2. Royal Gold & Dark Luxury Template
  {
    id: 'reviews_royal_gold',
    title: 'الملكي الفاخر (Royal Luxury Gold)',
    description: 'تصميم أسود وذهبي فاخر وفاخر جداً للمطاعم الراقية والمراكز والمنشآت الفخمة.',
    format: 'a4_portrait',
    canvasWidth: 794,
    canvasHeight: 1123,
    backgroundColor: '#0f172a',
    isSystemPreset: true,
    elements: [
      {
        id: 'el-top-bg',
        type: 'shape_rect',
        name: 'الخلفية الداكنة الفاخرة',
        x: 0,
        y: 0,
        width: 794,
        height: 1123,
        zIndex: 1,
        backgroundColor: '#0f172a',
        backgroundGradient: {
          from: '#0f172a',
          to: '#1e293b',
          direction: 'to bottom'
        }
      },
      {
        id: 'el-logo',
        type: 'logo',
        name: 'شعار المنشأة',
        x: 347,
        y: 40,
        width: 100,
        height: 100,
        zIndex: 10,
        borderRadius: 99,
        borderWidth: 3,
        borderColor: '#f59e0b',
        clipShape: 'circle'
      },
      {
        id: 'el-biz-name',
        type: 'business_name',
        name: 'اسم المنشأة',
        x: 50,
        y: 155,
        width: 694,
        height: 50,
        zIndex: 10,
        text: '{{business_name}}',
        fontSize: 34,
        fontWeight: '900',
        fontFamily: 'Cairo, sans-serif',
        color: '#fef08a',
        textAlign: 'center'
      },
      {
        id: 'el-rating-stars',
        type: 'rating_badge',
        name: 'شارة النجوم والتاج الملكي',
        x: 237,
        y: 215,
        width: 320,
        height: 40,
        zIndex: 10,
        text: '👑 ⭐⭐⭐⭐⭐ خدمة ملكية فاخرة',
        fontSize: 15,
        fontWeight: '800',
        fontFamily: 'Cairo, sans-serif',
        color: '#fbbf24',
        backgroundColor: '#451a03',
        borderRadius: 99,
        borderColor: '#f59e0b',
        borderWidth: 2,
        textAlign: 'center'
      },
      {
        id: 'el-scan-card',
        type: 'shape_rect',
        name: 'بطاقة QR الذهبية',
        x: 97,
        y: 285,
        width: 600,
        height: 520,
        zIndex: 5,
        backgroundColor: '#1e293b',
        borderRadius: 36,
        borderWidth: 2,
        borderColor: '#f59e0b',
        boxShadow: '0 25px 50px -12px rgba(245, 158, 11, 0.25)'
      },
      {
        id: 'el-qr-box',
        type: 'qr_code',
        name: 'رمز الـ QR الذهبي',
        x: 247,
        y: 320,
        width: 300,
        height: 300,
        zIndex: 15,
        qrColor: '#1e1b4b',
        qrBgColor: '#ffffff',
        qrCenterLogo: true,
        borderRadius: 24,
        borderColor: '#f59e0b',
        borderWidth: 5,
        padding: 18,
        boxShadow: '0 20px 30px rgba(0, 0, 0, 0.4)'
      },
      {
        id: 'el-scan-title',
        type: 'hero_title',
        name: 'عنوان التقييم الملكي',
        x: 120,
        y: 640,
        width: 554,
        height: 50,
        zIndex: 12,
        text: 'رأيكم يوجّـج تميّـزنا ✨',
        fontSize: 32,
        fontWeight: '900',
        fontFamily: 'Cairo, sans-serif',
        color: '#ffffff',
        textAlign: 'center'
      },
      {
        id: 'el-scan-sub',
        type: 'subtitle',
        name: 'وصف التقييم الملكي',
        x: 130,
        y: 698,
        width: 534,
        height: 50,
        zIndex: 12,
        text: 'امسح الرمز بكاميرا هاتفك وشاركنا انطباعك وتجربتك الفاخرة',
        fontSize: 16,
        fontWeight: '600',
        fontFamily: 'Cairo, sans-serif',
        color: '#cbd5e1',
        textAlign: 'center'
      },
      {
        id: 'el-gift-badge',
        type: 'shape_badge',
        name: 'شارة كود الخصم الملكي',
        x: 147,
        y: 830,
        width: 500,
        height: 54,
        zIndex: 12,
        text: '🎁 كود خصم خاص بانتظاركم فور تقديم التقييم!',
        fontSize: 16,
        fontWeight: '800',
        fontFamily: 'Cairo, sans-serif',
        color: '#fef08a',
        backgroundColor: '#78350f',
        borderRadius: 20,
        borderColor: '#f59e0b',
        borderWidth: 2,
        textAlign: 'center'
      },
      {
        id: 'el-bottom-note',
        type: 'custom_text',
        name: 'عبارة الشكر والتقدير',
        x: 50,
        y: 920,
        width: 694,
        height: 40,
        zIndex: 10,
        text: 'نشكركم لكونكم جزءاً من عائلتنا المميزة ❤️',
        fontSize: 18,
        fontWeight: '800',
        fontFamily: 'Cairo, sans-serif',
        color: '#94a3b8',
        textAlign: 'center'
      },
      {
        id: 'el-footer-branding',
        type: 'platform_branding',
        name: 'هوية المنصة وشعار شو في بإربد',
        x: 50,
        y: 1040,
        width: 694,
        height: 50,
        zIndex: 20,
        text: 'تم الإصدار عبر منصة شوف إربد الرقمية • shoofirbid.com',
        fontSize: 13,
        fontWeight: '700',
        color: '#64748b',
        textAlign: 'center'
      }
    ]
  },

  // 3. Vibrant Coral & Sunset Modern Template
  {
    id: 'reviews_vibrant_coral',
    title: 'العصري المبهج (Vibrant Coral)',
    description: 'تصميم حيوي وعصري بألوان مرجانية وبنفسجية جذابة جداً للكافيهات والمحلات والمراكز الشبابية.',
    format: 'a4_portrait',
    canvasWidth: 794,
    canvasHeight: 1123,
    backgroundColor: '#fafaf9',
    isSystemPreset: true,
    elements: [
      {
        id: 'el-top-wave',
        type: 'shape_rect',
        name: 'خلفية الهيدر المرجاني',
        x: 0,
        y: 0,
        width: 794,
        height: 280,
        zIndex: 1,
        backgroundColor: '#f43f5e',
        backgroundGradient: {
          from: '#f43f5e',
          to: '#e11d48',
          direction: 'to bottom'
        },
        borderRadius: 40
      },
      {
        id: 'el-logo',
        type: 'logo',
        name: 'شعار المنشأة',
        x: 630,
        y: 40,
        width: 100,
        height: 100,
        zIndex: 10,
        borderRadius: 24,
        borderWidth: 3,
        borderColor: '#ffffff',
        clipShape: 'rounded'
      },
      {
        id: 'el-biz-name',
        type: 'business_name',
        name: 'اسم المنشأة',
        x: 100,
        y: 50,
        width: 500,
        height: 50,
        zIndex: 10,
        text: '{{business_name}}',
        fontSize: 34,
        fontWeight: '900',
        fontFamily: 'Cairo, sans-serif',
        color: '#ffffff',
        textAlign: 'right'
      },
      {
        id: 'el-top-sub',
        type: 'custom_text',
        name: 'شعارات الملاحظات',
        x: 100,
        y: 105,
        width: 500,
        height: 36,
        zIndex: 10,
        text: '🌟 نسعد بآرائكم وملاحظاتكم الثمينة',
        fontSize: 16,
        fontWeight: '700',
        fontFamily: 'Cairo, sans-serif',
        color: '#fecdd3',
        textAlign: 'right'
      },
      {
        id: 'el-scan-card',
        type: 'shape_rect',
        name: 'بطاقة المسح العائمة',
        x: 60,
        y: 200,
        width: 674,
        height: 640,
        zIndex: 5,
        backgroundColor: '#ffffff',
        borderRadius: 40,
        borderWidth: 2,
        borderColor: '#ffe4e6',
        boxShadow: '0 25px 50px -12px rgba(244, 63, 94, 0.15)'
      },
      {
        id: 'el-qr-box',
        type: 'qr_code',
        name: 'رمز الـ QR المرجاني',
        x: 237,
        y: 240,
        width: 320,
        height: 320,
        zIndex: 15,
        qrColor: '#e11d48',
        qrBgColor: '#ffffff',
        qrCenterLogo: true,
        borderRadius: 28,
        borderColor: '#f43f5e',
        borderWidth: 4,
        padding: 20,
        boxShadow: '0 20px 30px rgba(244, 63, 94, 0.2)'
      },
      {
        id: 'el-scan-title',
        type: 'hero_title',
        name: 'عنوان التقييم العصري',
        x: 90,
        y: 585,
        width: 614,
        height: 55,
        zIndex: 12,
        text: 'صوتـك يهمّـنا ورأيـك يصنـع الفـرق! 🚀',
        fontSize: 30,
        fontWeight: '900',
        fontFamily: 'Cairo, sans-serif',
        color: '#9f1239',
        textAlign: 'center'
      },
      {
        id: 'el-scan-sub',
        type: 'subtitle',
        name: 'وصف التقييم العصري',
        x: 100,
        y: 645,
        width: 594,
        height: 50,
        zIndex: 12,
        text: 'امسح الرمز بسرعة لتسجيل تجربتك واقتراحاتك مباشرة',
        fontSize: 16,
        fontWeight: '600',
        fontFamily: 'Cairo, sans-serif',
        color: '#475569',
        textAlign: 'center'
      },
      {
        id: 'el-gift-badge',
        type: 'shape_badge',
        name: 'شارة برنامج المكافآت العصرية',
        x: 112,
        y: 725,
        width: 570,
        height: 52,
        zIndex: 12,
        text: '🎁 كود خصم فوري كهدية بسيطة تقديراً لوقتك!',
        fontSize: 15,
        fontWeight: '800',
        fontFamily: 'Cairo, sans-serif',
        color: '#047857',
        backgroundColor: '#d1fae5',
        borderRadius: 20,
        borderColor: '#a7f3d0',
        borderWidth: 2,
        textAlign: 'center'
      },
      {
        id: 'el-bottom-stars',
        type: 'rating_badge',
        name: 'نجوم التقييم المبهجة',
        x: 212,
        y: 875,
        width: 370,
        height: 48,
        zIndex: 10,
        text: '⭐⭐⭐⭐⭐ نكبر بثقتكم ودعمكم',
        fontSize: 17,
        fontWeight: '900',
        fontFamily: 'Cairo, sans-serif',
        color: '#be123c',
        backgroundColor: '#ffe4e6',
        borderRadius: 99,
        borderColor: '#fecdd3',
        borderWidth: 2,
        textAlign: 'center'
      },
      {
        id: 'el-footer-branding',
        type: 'platform_branding',
        name: 'هوية المنصة وشعار شو في بإربد',
        x: 50,
        y: 1040,
        width: 694,
        height: 50,
        zIndex: 20,
        text: 'تم الإصدار عبر منصة شوف إربد الرقمية • shoofirbid.com',
        fontSize: 13,
        fontWeight: '700',
        color: '#64748b',
        textAlign: 'center'
      }
    ]
  },

  // 4. Professional Medical & Healthcare Teal Template
  {
    id: 'reviews_medical_teal',
    title: 'الطبي والصحي الاحترافي (Clinical Medical)',
    description: 'تصميم طبي وهادئ وموثوق مخصص للعيادات، المراكز الطبية، الصيدليات والمختبرات.',
    format: 'a4_portrait',
    canvasWidth: 794,
    canvasHeight: 1123,
    backgroundColor: '#f0fdf4',
    isSystemPreset: true,
    elements: [
      {
        id: 'el-top-header',
        type: 'shape_rect',
        name: 'الهيدر الطبي الأزرق التركوازي',
        x: 0,
        y: 0,
        width: 794,
        height: 180,
        zIndex: 1,
        backgroundColor: '#0d9488',
        backgroundGradient: {
          from: '#0d9488',
          to: '#0f766e',
          direction: 'to bottom'
        }
      },
      {
        id: 'el-logo',
        type: 'logo',
        name: 'شعار العيادة / المنشأة الطبية',
        x: 630,
        y: 35,
        width: 105,
        height: 105,
        zIndex: 10,
        borderRadius: 24,
        borderWidth: 3,
        borderColor: '#ffffff',
        clipShape: 'rounded'
      },
      {
        id: 'el-biz-name',
        type: 'business_name',
        name: 'اسم العيادة الطبية',
        x: 100,
        y: 45,
        width: 500,
        height: 50,
        zIndex: 10,
        text: '{{business_name}}',
        fontSize: 34,
        fontWeight: '900',
        fontFamily: 'Cairo, sans-serif',
        color: '#ffffff',
        textAlign: 'right'
      },
      {
        id: 'el-med-badge',
        type: 'custom_text',
        name: 'شارة العناية والرعاية',
        x: 100,
        y: 100,
        width: 500,
        height: 36,
        zIndex: 10,
        text: '🩺 عيادتكم الموثوقة • رعاية صحية متكاملة',
        fontSize: 15,
        fontWeight: '700',
        fontFamily: 'Cairo, sans-serif',
        color: '#ccfbf1',
        textAlign: 'right'
      },
      {
        id: 'el-scan-card',
        type: 'shape_rect',
        name: 'بطاقة المراجعات الطبية',
        x: 50,
        y: 210,
        width: 694,
        height: 610,
        zIndex: 5,
        backgroundColor: '#ffffff',
        borderRadius: 36,
        borderWidth: 2,
        borderColor: '#99f6e4',
        boxShadow: '0 20px 40px -10px rgba(13, 148, 136, 0.12)'
      },
      {
        id: 'el-qr-box',
        type: 'qr_code',
        name: 'رمز الـ QR الطبي',
        x: 242,
        y: 250,
        width: 310,
        height: 310,
        zIndex: 15,
        qrColor: '#0f766e',
        qrBgColor: '#ffffff',
        qrCenterLogo: true,
        borderRadius: 28,
        borderColor: '#0d9488',
        borderWidth: 4,
        padding: 18,
        boxShadow: '0 15px 30px rgba(13, 148, 136, 0.15)'
      },
      {
        id: 'el-scan-title',
        type: 'hero_title',
        name: 'عنوان التقييم الطبي',
        x: 80,
        y: 585,
        width: 634,
        height: 50,
        zIndex: 12,
        text: 'صحتكم ورضاكم غايتنا الأولى 💚',
        fontSize: 32,
        fontWeight: '900',
        fontFamily: 'Cairo, sans-serif',
        color: '#0f766e',
        textAlign: 'center'
      },
      {
        id: 'el-scan-sub',
        type: 'subtitle',
        name: 'وصف التقييم الطبي',
        x: 80,
        y: 642,
        width: 634,
        height: 55,
        zIndex: 12,
        text: 'شاركونا تجربتكم وانطباعكم عن العناية الطبية لمساعدتنا في تقديم الأفضل دائماً',
        fontSize: 15,
        fontWeight: '600',
        fontFamily: 'Cairo, sans-serif',
        color: '#334155',
        textAlign: 'center',
        lineHeight: 1.5
      },
      {
        id: 'el-gift-badge',
        type: 'shape_badge',
        name: 'شارة خصم الفحص والمراجعة',
        x: 112,
        y: 720,
        width: 570,
        height: 52,
        zIndex: 12,
        text: '🎁 قسيمة خصم تشجيعية كهدية تقديراً لرأيك الكريم!',
        fontSize: 15,
        fontWeight: '800',
        fontFamily: 'Cairo, sans-serif',
        color: '#065f46',
        backgroundColor: '#d1fae5',
        borderRadius: 18,
        borderColor: '#6ee7b7',
        borderWidth: 2,
        textAlign: 'center'
      },
      {
        id: 'el-bottom-notes',
        type: 'custom_text',
        name: 'ملاحظة السلامة والامان',
        x: 50,
        y: 860,
        width: 694,
        height: 40,
        zIndex: 10,
        text: 'جميع الملاحظات تؤخذ ببالغ الاهتمام لتطوير جودة الرعاية الصحية 🏥',
        fontSize: 16,
        fontWeight: '800',
        fontFamily: 'Cairo, sans-serif',
        color: '#0d9488',
        textAlign: 'center'
      },
      {
        id: 'el-footer-branding',
        type: 'platform_branding',
        name: 'هوية المنصة وشعار شو في بإربد',
        x: 50,
        y: 1040,
        width: 694,
        height: 50,
        zIndex: 20,
        text: 'تم الإصدار عبر منصة شوف إربد الرقمية • shoofirbid.com',
        fontSize: 13,
        fontWeight: '700',
        color: '#64748b',
        textAlign: 'center'
      }
    ]
  }
];

